MLIR: mlir::FlatAffineValueConstraints Class Reference
mlir::FlatAffineValueConstraints Class Reference
An extension of FlatAffineConstraints in which dimensions and symbols can optionally be associated with an SSA value.
#include "mlir/Analysis/AffineStructures.h"
Public Member Functions
FlatAffineValueConstraints (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals, ArrayRef< Optional< Value >> valArgs={})
Constructs a constraint system reserving memory for the specified number of constraints and identifiers.
FlatAffineValueConstraints (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0, ArrayRef< Optional< Value >> valArgs={})
Constructs a constraint system with the specified number of dimensions and symbols.
FlatAffineValueConstraints (const FlatAffineConstraints &fac, ArrayRef< Optional< Value >> valArgs={})
FlatAffineValueConstraints (const AffineValueMap &avm)
Create a flat affine constraint system from an AffineValueMap or a list of these.
FlatAffineValueConstraints (ArrayRef< const AffineValueMap *> avmRef)
FlatAffineValueConstraints (IntegerSet set)
Creates an affine constraint system from an IntegerSet.
FlatAffineValueConstraints (ArrayRef< const AffineValueMap *> avmRef, IntegerSet set)
Kind getKind () const override
Return the kind of this FlatAffineConstraints.
void reset (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals=0) override
Clears any existing data and reserves memory for the specified constraints.
void reset (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals, ArrayRef< Value > valArgs)
void reset (unsigned numDims, unsigned numSymbols, unsigned numLocals, ArrayRef< Value > valArgs)
std::unique_ptr< FlatAffineValueConstraints > clone () const
Clones this object.
LogicalResult addAffineForOpDomain (AffineForOp forOp)
Adds constraints (lower and upper bounds) for the specified 'affine.for' operation's Value using IR information stored in its bound maps.
LogicalResult addDomainFromSliceMaps (ArrayRef< AffineMap > lbMaps, ArrayRef< AffineMap > ubMaps, ArrayRef< Value > operands)
Adds constraints (lower and upper bounds) for each loop in the loop nest described by the bound maps lbMaps and ubMaps of a computation slice.
void addAffineIfOpDomain (AffineIfOp ifOp)
Adds constraints imposed by the affine.if operation.
LogicalResult addBound (BoundType type, unsigned pos, AffineMap boundMap, ValueRange operands)
Adds a bound for the identifier at the specified position with constraints being drawn from the specified bound map and operands.
void addBound (BoundType type, Value val, int64_t value)
Adds a constant bound for the identifier associated with the given Value.
void getIneqAsAffineValueMap (unsigned pos, unsigned ineqPos, AffineValueMap &vmap, MLIRContext *context) const
Returns the bound for the identifier at pos from the inequality at ineqPos as a 1-d affine value map (affine map + operands).
LogicalResult addSliceBounds (ArrayRef< Value > values, ArrayRef< AffineMap > lbMaps, ArrayRef< AffineMap > ubMaps, ArrayRef< Value > operands)
Adds slice lower bounds represented by lower bounds in lbMaps and upper bounds in ubMaps to each identifier in the constraint system which has a value in values.
bool findId (Value val, unsigned *pos) const
Looks up the position of the identifier with the specified Value.
bool containsId (Value val) const
Returns true if an identifier with the specified Value exists, false otherwise.
void swapId (unsigned posA, unsigned posB) override
Swap the posA^th identifier with the posB^th identifier.
unsigned insertDimId (unsigned pos, ValueRange vals)
Insert identifiers of the specified kind at position pos.
unsigned insertSymbolId (unsigned pos, ValueRange vals)
virtual unsigned insertId (IdKind kind, unsigned pos, unsigned num=1) override
unsigned insertId (IdKind kind, unsigned pos, ValueRange vals)
unsigned appendDimId (ValueRange vals)
Append identifiers of the specified kind after the last identifier of that kind.
unsigned appendSymbolId (ValueRange vals)
void addInductionVarOrTerminalSymbol (Value val)
Add the specified values as a dim or symbol id depending on its nature, if it already doesn't exist in the system.
AffineMap computeAlignedMap (AffineMap map, ValueRange operands) const
Align map with this constraint system based on operands.
LogicalResult composeMap (const AffineValueMap *vMap)
Composes the affine value map with this FlatAffineValueConstrains, adding the results of the map as dimensions at the front [0, vMap->getNumResults()) and with the dimensions set to the equalities specified by the value map.
void projectOut (Value val)
Projects out the identifier that is associate with Value.
void convertLoopIVSymbolsToDims ()
Changes all symbol identifiers which are loop IVs to dim identifiers.
LogicalResult unionBoundingBox (const FlatAffineValueConstraints &other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
void mergeAndAlignIdsWithOther (unsigned offset, FlatAffineValueConstraints *other)
Merge and align the identifiers of this and other starting at offset, so that both constraint systems get the union of the contained identifiers that is dimension-wise and symbol-wise unique; both constraint systems are updated so that they have the union of all identifiers, with this's original identifiers appearing first followed by any of other's identifiers that didn't appear in this.
bool areIdsAlignedWithOther (const FlatAffineValueConstraints &other)
Returns true if this constraint system and other are in the same space, i.e., if they are associated with the same set of identifiers, appearing in the same order.
void clearAndCopyFrom (const FlatAffineConstraints &other) override
Replaces the contents of this FlatAffineValueConstraints with other.
Value getValue (unsigned pos) const
Returns the Value associated with the pos^th identifier.
bool hasValue (unsigned pos) const
Returns true if the pos^th identifier has an associated Value.
bool hasValues () const
Returns true if at least one identifier has an associated Value.
void getValues (unsigned start, unsigned end, SmallVectorImpl< Value > *values) const
Returns the Values associated with identifiers in range [start, end).
void getAllValues (SmallVectorImpl< Value > *values) const
ArrayRef< Optional< Value > > getMaybeValues () const
ArrayRef< Optional< Value > > getMaybeDimValues () const
ArrayRef< Optional< Value > > getMaybeSymbolValues () const
ArrayRef< Optional< Value > > getMaybeDimAndSymbolValues () const
void setValue (unsigned pos, Value val)
Sets the Value associated with the pos^th identifier.
void setValues (unsigned start, unsigned end, ArrayRef< Value > values)
Sets the Values associated with the identifiers in the range [start, end).
void mergeSymbolIds (FlatAffineValueConstraints &other)
Merge and align symbols of this and other such that both get union of of symbols that are unique.
Public Member Functions inherited from mlir::FlatAffineConstraints
FlatAffineConstraints (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals)
Constructs a constraint system reserving memory for the specified number of constraints and identifiers.
FlatAffineConstraints (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
Constructs a constraint system with the specified number of dimensions and symbols.
FlatAffineConstraints (IntegerSet set)
Creates an affine constraint system from an IntegerSet.
FlatAffineConstraints (const MutableAffineMap &map)
virtual ~FlatAffineConstraints ()=default
bool isEmpty () const
Checks for emptiness by performing variable elimination on all identifiers, running the GCD test on each equality constraint, and checking for invalid constraints.
bool isEmptyByGCDTest () const
Runs the GCD test on all equality constraints.
bool isIntegerEmpty () const
Returns true if the set of constraints is found to have no solution, false if a solution exists.
Matrix getBoundedDirections () const
Returns a matrix where each row is a vector along which the polytope is bounded.
Optional< SmallVector< int64_t, 8 > > findIntegerSample () const
Find an integer sample point satisfying the constraints using a branch and bound algorithm with generalized basis reduction, with some additional processing using Simplex for unbounded sets.
bool containsPoint (ArrayRef< int64_t > point) const
Returns true if the given point satisfies the constraints, or false otherwise.
void getLocalReprs (std::vector< SmallVector< int64_t, 8 >> &dividends, SmallVector< unsigned, 4 > &denominators, std::vector< llvm::Optional< std::pair< unsigned, unsigned >>> &repr) const
Find pairs of inequalities identified by their position indices, using which an explicit representation for each local variable can be computed.
void getLocalReprs (std::vector< llvm::Optional< std::pair< unsigned, unsigned >>> &repr) const
void getLocalReprs (std::vector< SmallVector< int64_t, 8 >> &dividends, SmallVector< unsigned, 4 > &denominators) const
std::unique_ptr< FlatAffineConstraints > clone () const
LogicalResult addBound (BoundType type, unsigned pos, AffineMap boundMap)
Adds a bound for the identifier at the specified position with constraints being drawn from the specified bound map.
void addBound (BoundType type, unsigned pos, int64_t value)
Adds a constant bound for the specified identifier.
void addBound (BoundType type, ArrayRef< int64_t > expr, int64_t value)
Adds a constant bound for the specified expression.
IntegerSet getAsIntegerSet (MLIRContext *context) const
Returns the constraint system as an integer set.
void getSliceBounds (unsigned offset, unsigned num, MLIRContext *context, SmallVectorImpl< AffineMap > *lbMaps, SmallVectorImpl< AffineMap > *ubMaps)
Computes the lower and upper bounds of the first num dimensional identifiers (starting at offset) as an affine map of the remaining identifiers (dimensional and symbolic).
void addLocalFloorDiv (ArrayRef< int64_t > dividend, int64_t divisor)
Adds a new local identifier as the floordiv of an affine function of other identifiers, the coefficients of which are provided in dividend and with respect to a positive constant divisor.
LogicalResult composeMatchingMap (AffineMap other)
Composes an affine map whose dimensions and symbols match one to one with the dimensions and symbols of this FlatAffineConstraints.
void projectOut (unsigned pos, unsigned num)
Projects out (aka eliminates) num identifiers starting at position pos.
void projectOut (unsigned pos)
void setAndEliminate (unsigned pos, ArrayRef< int64_t > values)
Sets the values.size() identifiers starting at pos to the specified values and removes them.
void setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
LogicalResult constantFoldId (unsigned pos)
Tries to fold the specified identifier to a constant using a trivial equality detection; if successful, the constant is substituted for the identifier everywhere in the constraint system and then removed from the system.
void constantFoldIdRange (unsigned pos, unsigned num)
This method calls constantFoldId for the specified range of identifiers, num identifiers starting at position pos.
LogicalResult unionBoundingBox (const FlatAffineConstraints &other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
Optional< int64_t > getConstantBoundOnDimSize (unsigned pos, SmallVectorImpl< int64_t > *lb=nullptr, int64_t *boundFloorDivisor=nullptr, SmallVectorImpl< int64_t > *ub=nullptr, unsigned *minLbPos=nullptr, unsigned *minUbPos=nullptr) const
Returns the smallest known constant bound for the extent of the specified identifier (pos^th), i.e., the smallest known constant that is greater than or equal to 'exclusive upper bound' - 'lower bound' of the identifier.
Optional< int64_t > getConstantBound (BoundType type, unsigned pos) const
Returns the constant bound for the pos^th identifier if there is one; None otherwise.
std::pair< AffineMap, AffineMap > getLowerAndUpperBound (unsigned pos, unsigned offset, unsigned num, unsigned symStartPos, ArrayRef< AffineExpr > localExprs, MLIRContext *context) const
Gets the lower and upper bound of the offset + posth identifier treating [0, offset) U [offset + num, symStartPos) as dimensions and [symStartPos, getNumDimAndSymbolIds) as symbols, and pos lies in [0, num).
void removeIndependentConstraints (unsigned pos, unsigned num)
Removes constraints that are independent of (i.e., do not have a coefficient) identifiers in the range [pos, pos + num).
bool isHyperRectangular (unsigned pos, unsigned num) const
Returns true if the set can be trivially detected as being hyper-rectangular on the specified contiguous set of identifiers.
void removeTrivialRedundancy ()
Removes duplicate constraints, trivially true constraints, and constraints that can be detected as redundant as a result of differing only in their constant term part.
void removeRedundantInequalities ()
A more expensive check than removeTrivialRedundancy to detect redundant inequalities.
void removeRedundantConstraints ()
Removes redundant constraints using Simplex.
void convertDimToLocal (unsigned dimStart, unsigned dimLimit)
Converts identifiers in the column range [idStart, idLimit) to local variables.
void mergeLocalIds (FlatAffineConstraints &other)
Adds additional local ids to the sets such that they both have the union of the local ids in each set, without changing the set of points that lie in this and other.
Public Member Functions inherited from mlir::IntegerPolyhedron
IntegerPolyhedron (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals)
Constructs a constraint system reserving memory for the specified number of constraints and identifiers.
IntegerPolyhedron (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
Constructs a constraint system with the specified number of dimensions and symbols.
virtual ~IntegerPolyhedron ()=default
std::unique_ptr< IntegerPolyhedron > clone () const
void reset (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
void append (const IntegerPolyhedron &other)
Appends constraints from other into this.
int64_t atEq (unsigned i, unsigned j) const
Returns the value at the specified equality row and column.
int64_t & atEq (unsigned i, unsigned j)
int64_t atIneq (unsigned i, unsigned j) const
Returns the value at the specified inequality row and column.
int64_t & atIneq (unsigned i, unsigned j)
unsigned getNumConstraints () const
unsigned getNumIds () const
unsigned getNumDimIds () const
unsigned getNumSymbolIds () const
unsigned getNumDimAndSymbolIds () const
unsigned getNumLocalIds () const
unsigned getNumCols () const
Returns the number of columns in the constraint system.
unsigned getNumEqualities () const
unsigned getNumInequalities () const
unsigned getNumReservedEqualities () const
unsigned getNumReservedInequalities () const
ArrayRef< int64_t > getEquality (unsigned idx) const
ArrayRef< int64_t > getInequality (unsigned idx) const
unsigned insertDimId (unsigned pos, unsigned num=1)
Insert num identifiers of the specified kind at position pos.
unsigned insertSymbolId (unsigned pos, unsigned num=1)
unsigned insertLocalId (unsigned pos, unsigned num=1)
unsigned appendDimId (unsigned num=1)
Append num identifiers of the specified kind after the last identifier.
unsigned appendSymbolId (unsigned num=1)
unsigned appendLocalId (unsigned num=1)
void addInequality (ArrayRef< int64_t > inEq)
Adds an inequality (>= 0) from the coefficients specified in inEq.
void addEquality (ArrayRef< int64_t > eq)
Adds an equality from the coefficients specified in eq.
void removeId (IdKind kind, unsigned pos)
Removes identifiers of the specified kind with the specified pos (or within the specified range) from the system.
void removeIdRange (IdKind kind, unsigned idStart, unsigned idLimit)
void removeId (unsigned pos)
Removes the specified identifier from the system.
void removeEquality (unsigned pos)
void removeInequality (unsigned pos)
void removeEqualityRange (unsigned start, unsigned end)
Remove the (in)equalities at positions [start, end).
void removeInequalityRange (unsigned start, unsigned end)
void clearConstraints ()
Removes all equalities and inequalities.
void getLowerAndUpperBoundIndices (unsigned pos, SmallVectorImpl< unsigned > *lbIndices, SmallVectorImpl< unsigned > *ubIndices, SmallVectorImpl< unsigned > *eqIndices=nullptr, unsigned offset=0, unsigned num=0) const
Gather positions of all lower and upper bounds of the identifier at pos, and optionally any equalities on it.
void print (raw_ostream &os) const
void dump () const
Static Public Member Functions
static FlatAffineValueConstraints getHyperrectangular (ValueRange ivs, ValueRange lbs, ValueRange ubs)
static bool classof (const FlatAffineConstraints *cst)
Static Public Member Functions inherited from mlir::FlatAffineConstraints
static FlatAffineConstraints getUniverse (unsigned numDims=0, unsigned numSymbols=0)
Return a system with no constraints, i.e., one which is satisfied by all points.
static bool classof (const FlatAffineConstraints *cst)
Protected Member Functions
bool hasConsistentState () const override
Returns false if the fields corresponding to various identifier counts, or equality/inequality buffer sizes aren't consistent; true otherwise.
virtual void removeIdRange (unsigned idStart, unsigned idLimit) override
Removes identifiers in the column range [idStart, idLimit), and copies any remaining valid data into place, updates member variables, and resizes arrays as needed.
void fourierMotzkinEliminate (unsigned pos, bool darkShadow=false, bool *isResultIntegerExact=nullptr) override
Eliminates the identifier at the specified position using Fourier-Motzkin variable elimination, but uses Gaussian elimination if there is an equality involving that identifier.
Protected Member Functions inherited from mlir::FlatAffineConstraints
bool hasInvalidConstraint () const
Checks all rows of equality/inequality constraints for trivial contradictions (for example: 1 == 0, 0 >= 1), which may have surfaced after elimination.
template<bool isLower>
Optional< int64_t > computeConstantLowerOrUpperBound (unsigned pos)
Returns the constant lower bound bound if isLower is true, and the upper bound if isLower is false.
LogicalResult flattenAlignedMapAndMergeLocals (AffineMap map, std::vector< SmallVector< int64_t, 8 >> *flattenedExprs)
Given an affine map that is aligned with this constraint system:
LogicalResult gaussianEliminateId (unsigned position)
Eliminates a single identifier at position from equality and inequality constraints.
void removeRedundantLocalVars ()
Removes local variables using equalities.
unsigned gaussianEliminateIds (unsigned posStart, unsigned posLimit)
Eliminates identifiers from equality and inequality constraints in column range [posStart, posLimit).
void gcdTightenInequalities ()
Tightens inequalities given that we are dealing with integer spaces.
void normalizeConstraintsByGCD ()
Normalized each constraints by the GCD of its coefficients.
bool findConstraintWithNonZeroAt (unsigned colIdx, bool isEq, unsigned *rowIdx) const
Searches for a constraint with a non-zero coefficient at colIdx in equality (isEq=true) or inequality (isEq=false) constraints.
bool isColZero (unsigned pos) const
Returns true if the pos^th column is all zero for both inequalities and equalities.
void printSpace (raw_ostream &os) const override
Prints the number of constraints, dimensions, symbols and locals in the FlatAffineConstraints.
Protected Member Functions inherited from mlir::IntegerPolyhedron
unsigned getIdKindOffset (IdKind kind) const
Return the index at which the specified kind of id starts.
unsigned getNumIdKind (IdKind kind) const
Get the number of ids of the specified kind.
Protected Attributes
SmallVector< Optional< Value >, 8 > values
Values corresponding to the (column) identifiers of this constraint system appearing in the order the identifiers correspond to columns.
Protected Attributes inherited from mlir::IntegerPolyhedron
unsigned numIds
Total number of identifiers.
unsigned numDims
Number of identifiers corresponding to real dimensions.
unsigned numSymbols
Number of identifiers corresponding to symbols (unknown but constant for analysis).
Matrix equalities
Coefficients of affine equalities (in == 0 form).
Matrix inequalities
Coefficients of affine inequalities (in >= 0 form).
Additional Inherited Members
Public Types inherited from mlir::FlatAffineConstraints
enum Kind { Kind::FlatAffineConstraints, Kind::FlatAffineValueConstraints }
All derived classes of FlatAffineConstraints.
enum BoundType { EQ, LB, UB }
The type of bound: equal, lower bound or upper bound.
Public Types inherited from mlir::IntegerPolyhedron
enum IdKind { Dimension, Symbol, Local }
Kind of identifier (column).
Static Protected Attributes inherited from mlir::FlatAffineConstraints
static constexpr unsigned kExplosionFactor = 32
A parameter that controls detection of an unrealistic number of constraints.
Detailed Description
An extension of FlatAffineConstraints in which dimensions and symbols can optionally be associated with an SSA value.
Definition at line 434 of file AffineStructures.h.
Constructor & Destructor Documentation
FlatAffineValueConstraints() [1/7]
mlir::FlatAffineValueConstraints::FlatAffineValueConstraints (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals, ArrayRef< Optional< Value >> valArgs = {}) inline
Constructs a constraint system reserving memory for the specified number of constraints and identifiers.
Definition at line 438 of file AffineStructures.h.
References mlir::FlatAffineConstraints::FlatAffineConstraints, and mlir::IntegerPolyhedron::numIds.
Referenced by reset().
FlatAffineValueConstraints() [2/7]
mlir::FlatAffineValueConstraints::FlatAffineValueConstraints (unsigned numDims = 0, unsigned numSymbols = 0, unsigned numLocals = 0, ArrayRef< Optional< Value >> valArgs = {}) inline
Constructs a constraint system with the specified number of dimensions and symbols.
Definition at line 456 of file AffineStructures.h.
References mlir::FlatAffineConstraints::FlatAffineValueConstraints.
FlatAffineValueConstraints() [3/7]
mlir::FlatAffineValueConstraints::FlatAffineValueConstraints (const FlatAffineConstraints & fac, ArrayRef< Optional< Value >> valArgs = {}) inline
Definition at line 465 of file AffineStructures.h.
References mlir::FlatAffineConstraints::FlatAffineConstraints, mlir::FlatAffineConstraints::FlatAffineValueConstraints, and mlir::IntegerPolyhedron::numIds.
FlatAffineValueConstraints() [4/7]
mlir::FlatAffineValueConstraints::FlatAffineValueConstraints (const AffineValueMap & avm) explicit
Create a flat affine constraint system from an AffineValueMap or a list of these.
The constructed system will only include equalities.
FlatAffineValueConstraints() [5/7]
mlir::FlatAffineValueConstraints::FlatAffineValueConstraints (ArrayRef< const AffineValueMap *> avmRef) explicit
FlatAffineValueConstraints() [6/7]
FlatAffineValueConstraints::FlatAffineValueConstraints (IntegerSet set) explicit
Creates an affine constraint system from an IntegerSet.
Definition at line 190 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::numIds, and values.
FlatAffineValueConstraints() [7/7]
mlir::FlatAffineValueConstraints::FlatAffineValueConstraints (ArrayRef< const AffineValueMap *> avmRef, IntegerSet set)
Member Function Documentation
addAffineForOpDomain()
LogicalResult FlatAffineValueConstraints::addAffineForOpDomain (AffineForOp forOp)
Adds constraints (lower and upper bounds) for the specified 'affine.for' operation's Value using IR information stored in its bound maps.
The right identifier is first looked up using forOp's Value. Asserts if the Value corresponding to the 'affine.for' operation isn't found in the constraint system. Returns failure for the yet unimplemented/unsupported cases. Any new identifiers that are found in the bound operands of the 'affine.for' operation are added as trailing identifiers (either dimensional or symbolic depending on whether the operand is a valid symbol).
Definition at line 585 of file AffineStructures.cpp.
References addBound(), mlir::IntegerPolyhedron::addEquality(), mlir::FlatAffineConstraints::addLocalFloorDiv(), mlir::failed(), mlir::failure(), findId(), mlir::IntegerPolyhedron::getNumCols(), and mlir::success().
Referenced by addDomainFromSliceMaps(), addInductionVarOrTerminalSymbol(), addMissingLoopIVBounds(), addSliceBounds(), mlir::ComputationSliceState::getAsConstraints(), mlir::getIndexSet(), mlir::ComputationSliceState::getSourceAsConstraints(), and mlir::ComputationSliceState::isMaximal().
addAffineIfOpDomain()
void FlatAffineValueConstraints::addAffineIfOpDomain (AffineIfOp ifOp)
Adds constraints imposed by the affine.if operation.
These constraints are collected from the IntegerSet attached to the given affine.if instance argument (ifOp). It is asserted that: 1) The IntegerSet of the given affine.if instance should not contain semi-affine expressions, 2) The columns of the constraint system created from ifOp should match the columns in the current one regarding numbers and values.
Definition at line 686 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::append(), and mergeAndAlignIdsWithOther().
Referenced by mlir::getIndexSet().
addBound() [1/2]
LogicalResult FlatAffineValueConstraints::addBound (BoundType type, unsigned pos, AffineMap boundMap, ValueRange operands)
Adds a bound for the identifier at the specified position with constraints being drawn from the specified bound map and operands.
In case of an EQ bound, the bound map is expected to have exactly one result. In case of a LB/UB, the bound map may have more than one result, for each of which an inequality is added.
Definition at line 2115 of file AffineStructures.cpp.
References addInductionVarOrTerminalSymbol(), mlir::canonicalizeMapAndOperands(), computeAlignedMap(), mlir::fullyComposeAffineMapAndOperands(), and mlir::simplifyAffineMap().
Referenced by addAffineForOpDomain(), addBound(), addDomainFromSliceMaps(), addInductionVarOrTerminalSymbol(), addLoopRangeConstraints(), addSliceBounds(), alignAndAddBound(), canonicalizeMinMaxOp(), mlir::ComputationSliceState::getAsConstraints(), mlir::linalg::getUpperBoundForIndex(), and mlir::scf::rewritePeeledMinMaxOp().
addBound() [2/2]
void FlatAffineValueConstraints::addBound (BoundType type, Value val, int64_t value)
Adds a constant bound for the identifier associated with the given Value.
Definition at line 2267 of file AffineStructures.cpp.
References addBound(), and findId().
addDomainFromSliceMaps()
LogicalResult FlatAffineValueConstraints::addDomainFromSliceMaps (ArrayRef< AffineMap > lbMaps, ArrayRef< AffineMap > ubMaps, ArrayRef< Value > operands)
Adds constraints (lower and upper bounds) for each loop in the loop nest described by the bound maps lbMaps and ubMaps of a computation slice.
Every pair (lbMaps[i], ubMaps[i]) describes the bounds of a loop in the nest, sorted outer-to-inner. operands contains the bound operands for a single bound map. All the bound maps will use the same bound operands. Note that some loops described by a computation slice might not exist yet in the IR so the Value attached to those dimension identifiers might be empty. For that reason, this method doesn't perform Value look-ups to retrieve the dimension identifier positions. Instead, it assumes the position of the dim identifiers in the constraint system is the same as the position of the loop in the loop nest.
Definition at line 637 of file AffineStructures.cpp.
References addAffineForOpDomain(), addBound(), mlir::AffineExpr::dyn_cast(), mlir::failed(), mlir::failure(), mlir::getForInductionVarOwner(), mlir::IntegerPolyhedron::getNumDimIds(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineDimExpr::getPosition(), mlir::AffineMap::getResult(), mlir::AffineExpr::isa(), and mlir::success().
Referenced by mlir::ComputationSliceState::isMaximal().
addInductionVarOrTerminalSymbol()
void FlatAffineValueConstraints::addInductionVarOrTerminalSymbol (Value val)
Add the specified values as a dim or symbol id depending on its nature, if it already doesn't exist in the system.
val has to be either a terminal symbol or a loop IV, i.e., it cannot be the result affine.apply of any symbols or loop IVs. The identifier is added to the end of the existing dims or symbols. Additional information on the identifier is extracted from the IR and added to the constraint system.
Definition at line 562 of file AffineStructures.cpp.
References addAffineForOpDomain(), addBound(), appendDimId(), appendSymbolId(), containsId(), mlir::failed(), mlir::Value::getDefiningOp(), mlir::getForInductionVarOwner(), mlir::isForInductionVar(), and mlir::isTopLevelValue().
Referenced by addBound().
addSliceBounds()
LogicalResult FlatAffineValueConstraints::addSliceBounds (ArrayRef< Value > values, ArrayRef< AffineMap > lbMaps, ArrayRef< AffineMap > ubMaps, ArrayRef< Value > operands)
Adds slice lower bounds represented by lower bounds in lbMaps and upper bounds in ubMaps to each identifier in the constraint system which has a value in values.
Note that both lower/upper bounds share the same operand list operands. This function assumes values.size == lbMaps.size == ubMaps.size. Note that both lower/upper bounds use operands from operands.
Definition at line 2139 of file AffineStructures.cpp.
References addAffineForOpDomain(), addBound(), mlir::failed(), mlir::failure(), findId(), mlir::getForInductionVarOwner(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getResult(), and mlir::success().
Referenced by mlir::ComputationSliceState::getAsConstraints().
appendDimId()
unsigned FlatAffineValueConstraints::appendDimId (ValueRange vals)
Append identifiers of the specified kind after the last identifier of that kind.
The coefficient columns corresponding to the added identifiers are initialized to zero. vals are the Values corresponding to the identifiers. Return the position of the first added column.
Note: Empty Values are allowed in vals.
Definition at line 270 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::getNumDimIds(), and insertId().
Referenced by addInductionVarOrTerminalSymbol(), addLoopRangeConstraints(), canonicalizeMinMaxOp(), mlir::linalg::getUpperBoundForIndex(), mergeAndAlignIds(), and mlir::scf::rewritePeeledMinMaxOp().
appendSymbolId()
unsigned FlatAffineValueConstraints::appendSymbolId (ValueRange vals)
Definition at line 276 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::getNumSymbolIds(), and insertId().
Referenced by addInductionVarOrTerminalSymbol(), and alignAndAddBound().
areIdsAlignedWithOther()
bool FlatAffineValueConstraints::areIdsAlignedWithOther (const FlatAffineValueConstraints & other)
Returns true if this constraint system and other are in the same space, i.e., if they are associated with the same set of identifiers, appearing in the same order.
Calls areIdsAligned to check if two constraint systems have the same set of identifiers in the same order.
Returns false otherwise.
Definition at line 333 of file AffineStructures.cpp.
References areIdsAligned().
Referenced by mlir::computeSliceUnion().
classof()
static bool mlir::FlatAffineValueConstraints::classof (const FlatAffineConstraints * cst) inline static
Definition at line 503 of file AffineStructures.h.
References mlir::FlatAffineConstraints::addBound(), mlir::FlatAffineConstraints::clone(), mlir::FlatAffineConstraints::FlatAffineValueConstraints, mlir::FlatAffineConstraints::getKind(), mlir::IntegerPolyhedron::insertDimId(), mlir::IntegerPolyhedron::insertId(), mlir::IntegerPolyhedron::insertSymbolId(), mlir::IntegerPolyhedron::reset(), mlir::IntegerPolyhedron::swapId(), and value.
clearAndCopyFrom()
void FlatAffineValueConstraints::clearAndCopyFrom (const FlatAffineConstraints & other) override virtual
Replaces the contents of this FlatAffineValueConstraints with other.
Reimplemented from mlir::FlatAffineConstraints.
Definition at line 2673 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::numIds, and values.
Referenced by mlir::FlatAffineConstraints::fourierMotzkinEliminate().
clone()
std::unique_ptr< FlatAffineValueConstraints > FlatAffineValueConstraints::clone () const
Clones this object.
Definition at line 155 of file AffineStructures.cpp.
composeMap()
LogicalResult FlatAffineValueConstraints::composeMap (const AffineValueMap * vMap)
Composes the affine value map with this FlatAffineValueConstrains, adding the results of the map as dimensions at the front [0, vMap->getNumResults()) and with the dimensions set to the equalities specified by the value map.
Returns failure if the composition fails (when vMap is a semi-affine map). The vMap's operand Value's are used to look up the right positions in the FlatAffineConstraints with which to associate. Every operand of vMap should have a matching dim/symbol column in this constraint system (with the same associated Value).
Definition at line 443 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::composeMatchingMap(), computeAlignedMap(), mlir::AffineValueMap::getAffineMap(), and mlir::AffineValueMap::getOperands().
Referenced by mlir::linalg::getUpperBoundForIndex().
computeAlignedMap()
AffineMap FlatAffineValueConstraints::computeAlignedMap (AffineMap map, ValueRange operands) const
Align map with this constraint system based on operands.
Each operand must already have a corresponding dim/symbol in this constraint system.
Definition at line 2087 of file AffineStructures.cpp.
References mlir::alignAffineMapWithValues(), mlir::AffineMap::getNumInputs(), mlir::IntegerPolyhedron::numDims, mlir::IntegerPolyhedron::numSymbols, and values.
Referenced by addBound(), composeMap(), and mlir::linalg::getUpperBoundForIndex().
containsId()
bool FlatAffineValueConstraints::containsId (Value val) const
Returns true if an identifier with the specified Value exists, false otherwise.
Definition at line 2249 of file AffineStructures.cpp.
References values.
Referenced by addInductionVarOrTerminalSymbol(), mlir::ComputationSliceState::getAsConstraints(), and mlir::linalg::getUpperBoundForIndex().
convertLoopIVSymbolsToDims()
void FlatAffineValueConstraints::convertLoopIVSymbolsToDims ()
Changes all symbol identifiers which are loop IVs to dim identifiers.
Definition at line 549 of file AffineStructures.cpp.
References mlir::getForInductionVarOwner(), mlir::IntegerPolyhedron::getNumDimAndSymbolIds(), mlir::IntegerPolyhedron::getNumDimIds(), getValue(), hasValue(), and turnSymbolIntoDim().
Referenced by mlir::computeSliceUnion().
findId()
bool FlatAffineValueConstraints::findId (Value val, unsigned * pos) const
Looks up the position of the identifier with the specified Value.
Returns true if found (false otherwise). pos is set to the (column) position of the identifier.
Definition at line 2237 of file AffineStructures.cpp.
References values.
Referenced by addAffineForOpDomain(), addBound(), addSliceBounds(), mlir::MemRefAccess::getAccessRelation(), mlir::linalg::getUpperBoundForIndex(), mergeAndAlignIds(), mergeSymbolIds(), projectOut(), and turnSymbolIntoDim().
fourierMotzkinEliminate()
void FlatAffineValueConstraints::fourierMotzkinEliminate (unsigned pos, bool darkShadow = false, bool * isResultIntegerExact = nullptr) override protected virtual
Eliminates the identifier at the specified position using Fourier-Motzkin variable elimination, but uses Gaussian elimination if there is an equality involving that identifier.
If the result of the elimination is integer exact, *isResultIntegerExact is set to true. If darkShadow is set to true, a potential under approximation (subset) of the rational shadow / exact integer shadow is computed.
Reimplemented from mlir::FlatAffineConstraints.
Definition at line 2911 of file AffineStructures.cpp.
References mlir::FlatAffineConstraints::fourierMotzkinEliminate(), mlir::IntegerPolyhedron::getNumIds(), mlir::IntegerPolyhedron::numIds, and values.
Referenced by mlir::FlatAffineConstraints::projectOut(), and projectOut().
getAllValues()
void mlir::FlatAffineValueConstraints::getAllValues (SmallVectorImpl< Value > * values) const inline
Definition at line 728 of file AffineStructures.h.
References mlir::IntegerPolyhedron::numIds.
Referenced by mlir::linalg::getUpperBoundForIndex().
getHyperrectangular()
FlatAffineValueConstraints FlatAffineValueConstraints::getHyperrectangular (ValueRange ivs, ValueRange lbs, ValueRange ubs) static
Definition at line 207 of file AffineStructures.cpp.
getIneqAsAffineValueMap()
void FlatAffineValueConstraints::getIneqAsAffineValueMap (unsigned pos, unsigned ineqPos, AffineValueMap & vmap, MLIRContext * context) const
Returns the bound for the identifier at pos from the inequality at ineqPos as a 1-d affine value map (affine map + operands).
The returned affine value map can either be a lower bound or an upper bound depending on the sign of atIneq(ineqPos, pos). Asserts if the row at ineqPos does not involve the posth identifier.
Definition at line 3181 of file AffineStructures.cpp.
References computeLocalVars(), mlir::failed(), mlir::AffineMap::get(), mlir::getAffineExprFromFlatForm(), mlir::IntegerPolyhedron::getInequality(), mlir::IntegerPolyhedron::getNumCols(), mlir::IntegerPolyhedron::getNumDimAndSymbolIds(), mlir::IntegerPolyhedron::getNumDimIds(), mlir::IntegerPolyhedron::getNumIds(), mlir::IntegerPolyhedron::getNumInequalities(), mlir::IntegerPolyhedron::getNumLocalIds(), mlir::IntegerPolyhedron::getNumSymbolIds(), getValues(), mlir::IntegerPolyhedron::numDims, and mlir::AffineValueMap::reset().
Referenced by createFullTiles().
getKind()
Kind mlir::FlatAffineValueConstraints::getKind () const inline override virtual
Return the kind of this FlatAffineConstraints.
Reimplemented from mlir::FlatAffineConstraints.
Definition at line 501 of file AffineStructures.h.
References mlir::FlatAffineConstraints::FlatAffineValueConstraints.
getMaybeDimAndSymbolValues()
ArrayRef<Optional<Value> > mlir::FlatAffineValueConstraints::getMaybeDimAndSymbolValues () const inline
Definition at line 744 of file AffineStructures.h.
References mlir::IntegerPolyhedron::getNumDimIds(), and mlir::IntegerPolyhedron::getNumSymbolIds().
Referenced by canonicalizeMinMaxOp().
getMaybeDimValues()
ArrayRef<Optional<Value> > mlir::FlatAffineValueConstraints::getMaybeDimValues () const inline
Definition at line 736 of file AffineStructures.h.
References mlir::IntegerPolyhedron::getNumDimIds().
Referenced by alignAndAddBound(), and mlir::FlatAffineRelation::compose().
getMaybeSymbolValues()
ArrayRef<Optional<Value> > mlir::FlatAffineValueConstraints::getMaybeSymbolValues () const inline
Definition at line 740 of file AffineStructures.h.
References mlir::IntegerPolyhedron::getNumDimIds(), and mlir::IntegerPolyhedron::getNumSymbolIds().
Referenced by alignAndAddBound().
getMaybeValues()
ArrayRef<Optional<Value> > mlir::FlatAffineValueConstraints::getMaybeValues () const inline
Definition at line 732 of file AffineStructures.h.
Referenced by areIdsAligned(), areIdsUnique(), mergeAndAlignIds(), and unionBoundingBox().
getValue()
Value mlir::FlatAffineValueConstraints::getValue (unsigned pos) const inline
Returns the Value associated with the pos^th identifier.
Asserts if no Value identifier was associated.
Definition at line 706 of file AffineStructures.h.
Referenced by addMissingLoopIVBounds(), mlir::FlatAffineRelation::compose(), mlir::computeSliceUnion(), convertLoopIVSymbolsToDims(), mlir::MemRefAccess::getAccessRelation(), getCommonBlock(), mlir::getComputationSliceState(), getNumCommonLoops(), mergeAndAlignIds(), and mergeSymbolIds().
getValues()
void mlir::FlatAffineValueConstraints::getValues (unsigned start, unsigned end, SmallVectorImpl< Value > * values) const inline
Returns the Values associated with identifiers in range [start, end).
Asserts if no Value was associated with one of these identifiers.
Definition at line 719 of file AffineStructures.h.
References mlir::IntegerPolyhedron::numIds.
Referenced by mlir::computeSliceUnion(), createSeparationCondition(), generateCopy(), mlir::getComputationSliceState(), getIneqAsAffineValueMap(), mergeAndAlignIds(), and mergeSymbolIds().
hasConsistentState()
bool FlatAffineValueConstraints::hasConsistentState () const override protected virtual
Returns false if the fields corresponding to various identifier counts, or equality/inequality buffer sizes aren't consistent; true otherwise.
This is meant to be used within an assert internally.
Reimplemented from mlir::IntegerPolyhedron.
Definition at line 750 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::getNumIds(), mlir::IntegerPolyhedron::hasConsistentState(), and values.
Referenced by mlir::FlatAffineConstraints::fourierMotzkinEliminate(), mlir::FlatAffineConstraints::gaussianEliminateIds(), mlir::FlatAffineConstraints::hasInvalidConstraint(), and mlir::FlatAffineConstraints::isEmptyByGCDTest().
hasValue()
bool mlir::FlatAffineValueConstraints::hasValue (unsigned pos) const inline
Returns true if the pos^th identifier has an associated Value.
Definition at line 712 of file AffineStructures.h.
Referenced by mlir::FlatAffineRelation::compose(), and convertLoopIVSymbolsToDims().
hasValues()
bool FlatAffineValueConstraints::hasValues () const
Returns true if at least one identifier has an associated Value.
Definition at line 315 of file AffineStructures.cpp.
References values.
insertDimId()
unsigned FlatAffineValueConstraints::insertDimId (unsigned pos, ValueRange vals)
Insert identifiers of the specified kind at position pos.
Positions are relative to the kind of identifier. The coefficient columns corresponding to the added identifiers are initialized to zero. vals are the Values corresponding to the identifiers. Return the absolute column position (i.e., not relative to the kind of identifier) of the first added identifier.
Note: Empty Values are allowed in vals.
Definition at line 282 of file AffineStructures.cpp.
References insertId().
Referenced by mlir::FlatAffineRelation::appendDomainId(), mlir::FlatAffineRelation::appendRangeId(), mlir::FlatAffineConstraints::composeMatchingMap(), computeDirectionVector(), mlir::FlatAffineRelation::insertDomainId(), mlir::FlatAffineRelation::insertRangeId(), and mergeAndAlignIds().
insertId() [1/2]
unsigned FlatAffineValueConstraints::insertId (IdKind kind, unsigned pos, unsigned num = 1) override virtual
Reimplemented from mlir::IntegerPolyhedron.
Definition at line 292 of file AffineStructures.cpp.
Referenced by appendDimId(), appendSymbolId(), insertDimId(), and insertSymbolId().
insertId() [2/2]
unsigned FlatAffineValueConstraints::insertId (IdKind kind, unsigned pos, ValueRange vals)
Definition at line 300 of file AffineStructures.cpp.
insertSymbolId()
unsigned FlatAffineValueConstraints::insertSymbolId (unsigned pos, ValueRange vals)
Definition at line 287 of file AffineStructures.cpp.
References insertId().
Referenced by mergeSymbolIds().
mergeAndAlignIdsWithOther()
void FlatAffineValueConstraints::mergeAndAlignIdsWithOther (unsigned offset, FlatAffineValueConstraints * other)
Merge and align the identifiers of this and other starting at offset, so that both constraint systems get the union of the contained identifiers that is dimension-wise and symbol-wise unique; both constraint systems are updated so that they have the union of all identifiers, with this's original identifiers appearing first followed by any of other's identifiers that didn't appear in this.
Local identifiers in other that have the same division representation as local identifiers in this are merged into one.
Definition at line 437 of file AffineStructures.cpp.
References mergeAndAlignIds().
Referenced by addAffineIfOpDomain(), and mlir::computeSliceUnion().
mergeSymbolIds()
void FlatAffineValueConstraints::mergeSymbolIds (FlatAffineValueConstraints & other)
Merge and align symbols of this and other such that both get union of of symbols that are unique.
Symbols in this and other should be unique. Symbols with Value as None are considered to be inequal to all other symbols.
Definition at line 513 of file AffineStructures.cpp.
References areIdsUnique(), findId(), mlir::IntegerPolyhedron::getNumDimAndSymbolIds(), mlir::IntegerPolyhedron::getNumDimIds(), mlir::IntegerPolyhedron::getNumSymbolIds(), getValue(), getValues(), insertSymbolId(), and swapId().
Referenced by mlir::FlatAffineRelation::compose(), and mergeAndAlignIds().
projectOut()
void FlatAffineValueConstraints::projectOut (Value val)
Projects out the identifier that is associate with Value.
Definition at line 2959 of file AffineStructures.cpp.
References findId(), and fourierMotzkinEliminate().
Referenced by mlir::FlatAffineConstraints::computeConstantLowerOrUpperBound(), computeDirectionVector(), mlir::getComputationSliceState(), and mlir::ComputationSliceState::isSliceValid().
removeIdRange()
void FlatAffineValueConstraints::removeIdRange (unsigned idStart, unsigned idLimit) override protected virtual
Removes identifiers in the column range [idStart, idLimit), and copies any remaining valid data into place, updates member variables, and resizes arrays as needed.
Reimplemented from mlir::IntegerPolyhedron.
Reimplemented in mlir::FlatAffineRelation.
Definition at line 820 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::removeIdRange(), and values.
Referenced by mlir::FlatAffineConstraints::convertDimToLocal(), mlir::FlatAffineConstraints::gaussianEliminateIds(), mlir::FlatAffineRelation::inverse(), mlir::FlatAffineRelation::removeIdRange(), and mlir::FlatAffineConstraints::setAndEliminate().
reset() [1/3]
void FlatAffineValueConstraints::reset (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals = 0) override virtual
Clears any existing data and reserves memory for the specified constraints.
Reimplemented from mlir::IntegerPolyhedron.
Definition at line 237 of file AffineStructures.cpp.
Referenced by checkTilingLegalityImpl(), mlir::ComputationSliceState::getAsConstraints(), mlir::getIndexSet(), mlir::ComputationSliceState::getSourceAsConstraints(), mlir::ComputationSliceState::isMaximal(), and reset().
reset() [2/3]
void FlatAffineValueConstraints::reset (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals, ArrayRef< Value > valArgs)
Definition at line 247 of file AffineStructures.cpp.
References FlatAffineValueConstraints().
reset() [3/3]
void FlatAffineValueConstraints::reset (unsigned numDims, unsigned numSymbols, unsigned numLocals, ArrayRef< Value > valArgs)
Definition at line 262 of file AffineStructures.cpp.
References reset().
setValue()
void mlir::FlatAffineValueConstraints::setValue (unsigned pos, Value val) inline
Sets the Value associated with the pos^th identifier.
Definition at line 749 of file AffineStructures.h.
References mlir::IntegerPolyhedron::numIds.
Referenced by mlir::FlatAffineRelation::compose(), mlir::MemRefAccess::getAccessRelation(), and mlir::getRelationFromMap().
setValues()
void mlir::FlatAffineValueConstraints::setValues (unsigned start, unsigned end, ArrayRef< Value > values) inline
Sets the Values associated with the identifiers in the range [start, end).
Definition at line 755 of file AffineStructures.h.
References mlir::FlatAffineConstraints::fourierMotzkinEliminate(), mlir::IntegerPolyhedron::hasConsistentState(), mlir::IntegerPolyhedron::numIds, and mlir::IntegerPolyhedron::removeIdRange().
swapId()
void FlatAffineValueConstraints::swapId (unsigned posA, unsigned posB) override virtual
Swap the posA^th identifier with the posB^th identifier.
Reimplemented from mlir::IntegerPolyhedron.
Definition at line 2255 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::swapId(), and values.
Referenced by mlir::FlatAffineConstraints::convertDimToLocal(), mlir::MemRefAccess::getAccessRelation(), mlir::FlatAffineRelation::inverse(), mergeAndAlignIds(), mergeSymbolIds(), and turnSymbolIntoDim().
unionBoundingBox()
LogicalResult FlatAffineValueConstraints::unionBoundingBox (const FlatAffineValueConstraints & other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
For each of the dimensions, the min of the lower bounds (symbolic) and the max of the upper bounds (symbolic) is computed to determine such a bounding box. other is expected to have the same dimensional identifiers as this constraint system (in the same order).
E.g.: 1) this = {0 <= d0 <= 127}, other = {16 <= d0 <= 192}, output = {0 <= d0 <= 192} 2) this = {s0 + 5 <= d0 <= s0 + 20}, other = {s0 + 1 <= d0 <= s0 + 9}, output = {s0 + 1 <= d0 <= s0 + 20} 3) this = {0 <= d0 <= 5, 1 <= d1 <= 9} other = {2 <= d0 <= 6, 5 <= d1 <= 15}, output = {0 <= d0 <= 6, 1 <= d1 <= 15}
Definition at line 3128 of file AffineStructures.cpp.
References areIdsAligned(), getMaybeValues(), mlir::IntegerPolyhedron::getNumDimIds(), mlir::IntegerPolyhedron::getNumLocalIds(), mergeAndAlignIds(), mlir::IntegerPolyhedron::numDims, and mlir::FlatAffineConstraints::unionBoundingBox().
Referenced by mlir::computeSliceUnion().
Member Data Documentation
values
SmallVector<Optional<Value>, 8> mlir::FlatAffineValueConstraints::values protected
Values corresponding to the (column) identifiers of this constraint system appearing in the order the identifiers correspond to columns.
Temporary ones or those that aren't associated with any Value are set to None.
Definition at line 794 of file AffineStructures.h.
Referenced by clearAndCopyFrom(), mlir::FlatAffineRelation::compose(), computeAlignedMap(), containsId(), findId(), FlatAffineValueConstraints(), fourierMotzkinEliminate(), hasConsistentState(), hasValues(), removeIdRange(), and swapId().
The documentation for this class was generated from the following files:
include/mlir/Analysis/AffineStructures.h
lib/Analysis/AffineStructures.cpp