MLIR: mlir::linalg::comprehensive_bufferize::BufferizationState Class Reference
mlir::linalg::comprehensive_bufferize::BufferizationState Class Reference
BufferizationState provides a variety of helper functions for dealing with tensor values and memref buffers.
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.h"
Public Member Functions
BufferizationState (Operation *op, const BufferizationOptions &options)
BufferizationState (const BufferizationState &)=delete
SmallVector< OpOperand * > getAliasingOpOperand (OpResult result)
Determine which OpOperand* will alias with result if the op is bufferized in place.
OpResult getAliasingOpResult (OpOperand &opOperand)
Determine which OpResult will alias with opOperand if the op is bufferized in place.
bool bufferizesToMemoryRead (OpOperand &opOperand)
Return true if opOperand bufferizes to a memory read.
bool bufferizesToMemoryWrite (OpOperand &opOperand)
Return true if opOperand bufferizes to a memory write.
bool bufferizesToAliasOnly (OpOperand &opOperand)
Return true if opOperand does neither read nor write but bufferizes to an alias.
bool isValueRead (Value value)
Return true if the given value is read by an op that bufferizes to a memory read.
llvm::SetVector< Value > findValueInReverseUseDefChain (Value value, std::function< bool(Value)> condition)
Starting from value, follow the use-def chain in reverse, always selecting the aliasing OpOperands.
Value findLastPrecedingWrite (Value value)
Find the Value of the last preceding write of a given Value.
Optional< Value > createAlloc (OpBuilder &b, Location loc, MemRefType type, ArrayRef< Value > dynShape)
Creates a memref allocation.
Value createAllocDeallocPair (OpBuilder &builder, Location loc, Value shapedValue)
Creates an alloc-dealloc pair.
void createDealloc (OpBuilder &b, Location loc, Value allocatedBuffer)
Creates a memref deallocation.
void createMemCpy (OpBuilder &b, Location loc, Value from, Value to)
Creates a memcpy between two given buffers.
void replaceOp (Operation *op, ValueRange values)
Replace an op with replacement values.
template<typename OpTy , typename... Args>
OpTy replaceOpWithNewOp (OpBuilder &b, Operation *op, Args &&...args)
Replace an op with a new op.
Value lookupBuffer (Value tensor)
Lookup the memref buffer that is associated to the given tensor value.
bool isInPlace (OpResult opResult) const
Return true if the given OpResult has been decided to bufferize inplace.
Value getResultBuffer (OpResult result)
Return the result buffer (memref) for a given OpResult (tensor).
template<typename StateT >
StateT & getDialectState (StringRef name)
Return dialect-specific bufferization state.
const BufferizationOptions & getOptions () const
Return a reference to the BufferizationOptions.
OpBuilder & getBuilder ()
Return a reference to the OpBuilder.
Friends
LogicalResult runComprehensiveBufferize (Operation *op, const BufferizationOptions &options, BufferizationState &state, const PostAnalysisStepList &extraSteps)
LogicalResult runComprehensiveBufferize (ModuleOp moduleOp, const BufferizationOptions &options)
Bufferize the given module.
Detailed Description
BufferizationState provides a variety of helper functions for dealing with tensor values and memref buffers.
In particular, BufferizableOpInterface::bufferize implementation should utilize the following helper functions.
createAlloc / createDealloc / createAllocDeallocPair creates ops that allocate and/or deallocate memref buffers.
lookupBuffer returns the memref buffer of a given tensor value.
getResultBuffer returns the memref buffer for a given tensor OpResult. Based on inplace bufferization decisions of the analysis, it may either directly return a mapped buffer or allocate a new brand new buffer.
replaceOp replaces an op with new values.
Definition at line 297 of file BufferizableOpInterface.h.
Constructor & Destructor Documentation
BufferizationState() [1/2]
mlir::linalg::comprehensive_bufferize::BufferizationState::BufferizationState (Operation * op, const BufferizationOptions & options)
Definition at line 335 of file BufferizableOpInterface.cpp.
References mlir::WalkResult::advance(), getResultBuffer(), mlir::linalg::comprehensive_bufferize::BufferizationOptions::isOpAllowed(), mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::markInPlace(), mlir::WalkResult::skip(), mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::unionAliasSets(), and mlir::Operation::walk().
BufferizationState() [2/2]
mlir::linalg::comprehensive_bufferize::BufferizationState::BufferizationState (const BufferizationState &) delete
Member Function Documentation
bufferizesToAliasOnly()
bool mlir::linalg::comprehensive_bufferize::BufferizationState::bufferizesToAliasOnly (OpOperand & opOperand)
Return true if opOperand does neither read nor write but bufferizes to an alias.
Return false if the op is not bufferizable.
Definition at line 249 of file BufferizableOpInterface.cpp.
References mlir::detail::IROperandBase::getOwner().
Referenced by bufferizesToMemoryWrite().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::BufferizationState::bufferizesToMemoryRead (OpOperand & opOperand)
Return true if opOperand bufferizes to a memory read.
Return true if the op is not bufferizable.
Definition at line 223 of file BufferizableOpInterface.cpp.
References bufferizesToMemoryWrite(), and mlir::detail::IROperandBase::getOwner().
Referenced by getAliasingOpResult(), and getResultBuffer().
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::BufferizationState::bufferizesToMemoryWrite (OpOperand & opOperand)
Return true if opOperand bufferizes to a memory write.
Return true` if the op is not bufferizable.
Return true if the op is not bufferizable.
Definition at line 236 of file BufferizableOpInterface.cpp.
References bufferizesToAliasOnly(), and mlir::detail::IROperandBase::getOwner().
Referenced by bufferizesToMemoryRead(), and getResultBuffer().
createAlloc()
Optional< Value > mlir::linalg::comprehensive_bufferize::BufferizationState::createAlloc (OpBuilder & b, Location loc, MemRefType type, ArrayRef< Value > dynShape)
Creates a memref allocation.
Create a memref allocation.
Definition at line 629 of file BufferizableOpInterface.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationOptions::allocationFns.
Referenced by createAllocDeallocPair().
createAllocDeallocPair()
Value mlir::linalg::comprehensive_bufferize::BufferizationState::createAllocDeallocPair (OpBuilder & b, Location loc, Value shapedValue)
Creates an alloc-dealloc pair.
Create an Allocop/DeAllocOp pair, where the AllocOp is after shapedValue.getDefiningOp (or at the top of the block in case of a bbArg) and the DeallocOp is at the end of the block.
This function may perform additional optimizations such as buffer allocation hoisting.
Definition at line 601 of file BufferizableOpInterface.cpp.
References mlir::OpBuilder::create(), createAlloc(), createDealloc(), mlir::Type::dyn_cast(), getAllocationTypeAndShape(), mlir::Value::getType(), mlir::Type::isa(), and mlir::OpBuilder::setInsertionPoint().
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferize(), getAllocationTypeAndShape(), and getResultBuffer().
createDealloc()
void mlir::linalg::comprehensive_bufferize::BufferizationState::createDealloc (OpBuilder & b, Location loc, Value allocatedBuffer)
Creates a memref deallocation.
Create a memref deallocation.
The given memref buffer must have been allocated using createAlloc.
Definition at line 635 of file BufferizableOpInterface.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationOptions::allocationFns.
Referenced by createAllocDeallocPair().
createMemCpy()
void mlir::linalg::comprehensive_bufferize::BufferizationState::createMemCpy (OpBuilder & b, Location loc, Value from, Value to)
Creates a memcpy between two given buffers.
Create a memory copy between two memref buffers.
Definition at line 641 of file BufferizableOpInterface.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationOptions::allocationFns.
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::bufferize(), and getResultBuffer().
findLastPrecedingWrite()
Value mlir::linalg::comprehensive_bufferize::BufferizationState::findLastPrecedingWrite (Value value)
Find the Value of the last preceding write of a given Value.
Note: Unknown ops are handled conservatively and assumed to be writes. Furthermore, BlockArguments are also assumed to be writes. There is no analysis across block boundaries.
Note: When reaching an end of the reverse SSA use-def chain, that value is returned regardless of whether it is a memory write or not.
Definition at line 315 of file BufferizableOpInterface.cpp.
References mlir::Value::cast(), mlir::Value::getDefiningOp(), and options.
Referenced by findValueInReverseUseDefChain(), and getResultBuffer().
findValueInReverseUseDefChain()
llvm::SetVector< Value > mlir::linalg::comprehensive_bufferize::BufferizationState::findValueInReverseUseDefChain (Value value, std::function< bool(Value)> condition)
Starting from value, follow the use-def chain in reverse, always selecting the aliasing OpOperands.
Find and return Values for which condition evaluates to true. OpOperands of such matching Values are not traversed any further.
When reaching the end of a chain (BlockArgument or Value without aliasing OpOperands), also return the last Value of that chain.
Example:
                          8
                          |
6* 7* +--—+-—+ | | | | 2* 3 4* 5 | | | | +-------—+-------—+-------—+ | 1
In the above example, Values with a star satisfy the condition. When starting the traversal from Value 1, the resulting SetVector is: { 2, 7, 8, 5 }
Definition at line 287 of file BufferizableOpInterface.cpp.
References mlir::Value::cast(), findLastPrecedingWrite(), mlir::Value::getDefiningOp(), mlir::Value::isa(), and options.
Referenced by mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::eliminateInitTensors(), mlir::linalg::comprehensive_bufferize::tensor_ext::hasMatchingExtractSliceOp(), and isValueRead().
getAliasingOpOperand()
SmallVector< OpOperand * > mlir::linalg::comprehensive_bufferize::BufferizationState::getAliasingOpOperand (OpResult result)
Determine which OpOperand* will alias with result if the op is bufferized in place.
Return an empty vector if the op is not bufferizable.
Definition at line 201 of file BufferizableOpInterface.cpp.
References mlir::Value::getDefiningOp().
Referenced by mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::eliminateInitTensors(), and getResultBuffer().
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::BufferizationState::getAliasingOpResult (OpOperand & opOperand)
Determine which OpResult will alias with opOperand if the op is bufferized in place.
Return an empty OpResult if the op is not bufferizable.
Definition at line 212 of file BufferizableOpInterface.cpp.
References bufferizesToMemoryRead(), and mlir::detail::IROperandBase::getOwner().
getBuilder()
OpBuilder& mlir::linalg::comprehensive_bufferize::BufferizationState::getBuilder () inline
Return a reference to the OpBuilder.
Definition at line 421 of file BufferizableOpInterface.h.
References mlir::linalg::comprehensive_bufferize::bufferize(), mlir::linalg::comprehensive_bufferize::getContiguousMemRefType(), mlir::linalg::comprehensive_bufferize::getContiguousOrUnrankedMemRefType(), mlir::linalg::comprehensive_bufferize::getDynamicMemRefType(), options, and mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
Referenced by mlir::linalg::comprehensive_bufferize::bufferize(), lookupBuffer(), and replaceOp().
getDialectState()
template<typename StateT > StateT& mlir::linalg::comprehensive_bufferize::BufferizationState::getDialectState (StringRef name) inline
Return dialect-specific bufferization state.
Definition at line 410 of file BufferizableOpInterface.h.
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::getTensorBufferizationState().
getOptions()
const BufferizationOptions& mlir::linalg::comprehensive_bufferize::BufferizationState::getOptions () const inline
Return a reference to the BufferizationOptions.
Definition at line 418 of file BufferizableOpInterface.h.
References options.
Referenced by mlir::linalg::comprehensive_bufferize::bufferization_ext::ToMemrefOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::bufferize(), and mlir::linalg::comprehensive_bufferize::AllocationHoistingBarrierOnly< OpTy >::bufferize().
getResultBuffer()
Value mlir::linalg::comprehensive_bufferize::BufferizationState::getResultBuffer (OpResult result)
Return the result buffer (memref) for a given OpResult (tensor).
Allocate a new buffer and copy over data from the existing buffer if out-of-place bufferization is necessary.
Definition at line 363 of file BufferizableOpInterface.cpp.
References bufferizesToMemoryRead(), bufferizesToMemoryWrite(), mlir::Value::cast(), createAllocDeallocPair(), createMemCpy(), mlir::linalg::comprehensive_bufferize::BufferizationOptions::dynCastBufferizableOp(), mlir::Operation::emitError(), findLastPrecedingWrite(), mlir::IROperand< DerivedT, IRValueT >::get(), getAliasingOpOperand(), mlir::Operation::getLoc(), mlir::OpResult::getOwner(), mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::isInPlace(), isValueRead(), lookupBuffer(), mlir::OpBuilder::setInsertionPoint(), and setInsertionPointAfter().
Referenced by BufferizationState(), mlir::linalg::comprehensive_bufferize::tensor_ext::CastOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::vector_ext::TransferWriteOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::InsertOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferize(), and mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::bufferize().
isInPlace()
bool mlir::linalg::comprehensive_bufferize::BufferizationState::isInPlace (OpResult opResult) const
Return true if the given OpResult has been decided to bufferize inplace.
Definition at line 690 of file BufferizableOpInterface.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::isInPlace().
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferize(), and mlir::linalg::comprehensive_bufferize::tensor_ext::InplaceInsertSliceOpAnalysis::run().
isValueRead()
bool mlir::linalg::comprehensive_bufferize::BufferizationState::isValueRead (Value value)
Return true if the given value is read by an op that bufferizes to a memory read.
Also takes into account ops that create an alias but do not read by themselves (e.g., ExtractSliceOp).
Definition at line 262 of file BufferizableOpInterface.cpp.
References findValueInReverseUseDefChain(), and mlir::Value::getUses().
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferizesToMemoryRead(), and getResultBuffer().
lookupBuffer()
Value mlir::linalg::comprehensive_bufferize::BufferizationState::lookupBuffer (Value tensor)
Lookup the memref buffer that is associated to the given tensor value.
Asserts if no buffer is associated.
Definition at line 657 of file BufferizableOpInterface.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationOptions::allowUnknownOps, mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Value::dump(), mlir::linalg::comprehensive_bufferize::BufferizationOptions::dynCastBufferizableOp(), getBuilder(), mlir::Value::getDefiningOp(), mlir::linalg::comprehensive_bufferize::getDynamicMemRefType(), mlir::Value::getLoc(), mlir::Value::getType(), mlir::Type::isa(), mlir::linalg::comprehensive_bufferize::isFunctionArgument(), and setInsertionPointAfter().
Referenced by mlir::linalg::comprehensive_bufferize::vector_ext::TransferReadOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::DimOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::std_ext::ReturnOpInterface::bufferize(), and getResultBuffer().
replaceOp()
void mlir::linalg::comprehensive_bufferize::BufferizationState::replaceOp (Operation * op, ValueRange values)
Replace an op with replacement values.
The op is deleted. Tensor OpResults must be replaced with memref values.
Definition at line 426 of file BufferizableOpInterface.cpp.
References mlir::OpBuilder::create(), mlir::Operation::erase(), getBuilder(), mlir::Value::getLoc(), mlir::Operation::getOpResults(), mlir::Value::getType(), mlir::Type::isa(), and setInsertionPointAfter().
Referenced by mlir::linalg::comprehensive_bufferize::vector_ext::TransferReadOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::vector_ext::TransferWriteOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::scf_ext::IfOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractSliceOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::InsertOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferize(), and mlir::linalg::comprehensive_bufferize::tensor_ext::InsertSliceOpInterface::bufferize().
replaceOpWithNewOp()
template<typename OpTy , typename... Args> OpTy mlir::linalg::comprehensive_bufferize::BufferizationState::replaceOpWithNewOp (OpBuilder & b, Operation * op, Args &&... args) inline
Replace an op with a new op.
Tensor OpResults must be replaced with memref values.
Definition at line 390 of file BufferizableOpInterface.h.
References mlir::OpBuilder::create(), mlir::Operation::getLoc(), mlir::Operation::getResults(), and isInPlace().
Referenced by mlir::linalg::comprehensive_bufferize::arith_ext::ConstantOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::CastOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::tensor_ext::DimOpInterface::bufferize(), and mlir::linalg::comprehensive_bufferize::tensor_ext::ExtractOpInterface::bufferize().
Friends And Related Function Documentation
runComprehensiveBufferize [1/2]
LogicalResult runComprehensiveBufferize (Operation * op, const BufferizationOptions & options, BufferizationState & state, const PostAnalysisStepList & extraSteps) friend
runComprehensiveBufferize [2/2]
LogicalResult runComprehensiveBufferize (ModuleOp moduleOp, const BufferizationOptions & options) friend
Bufferize the given module.
This bufferizations performs a simple function call analysis to determine which function arguments are inplaceable.
The documentation for this class was generated from the following files:
include/mlir/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.h
lib/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.cpp