MLIR: lib/Dialect/Linalg/ComprehensiveBufferize/ComprehensiveBufferize.cpp File Reference
ComprehensiveBufferize.cpp File Reference
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/ComprehensiveBufferize.h"
#include <random>
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/Dominance.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/TypeUtilities.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SetVector.h"
Functions
static bool isaTensor (Type t)
static void setInPlaceOpResult (OpResult opResult, bool inPlace)
Mark whether OpResult can actually be bufferized inplace.
static bool isInplaceMemoryWrite (OpOperand &opOperand, const BufferizationAliasInfo &aliasInfo, BufferizationState &state)
Return true if opOperand has been decided to bufferize in-place.
static bool aliasesNonWritableBuffer (Value value, const BufferizationAliasInfo &aliasInfo, BufferizationState &state)
Return true if, under current bufferization decisions, the buffer of value is not writable.
static bool aliasesInPlaceWrite (Value value, const BufferizationAliasInfo &aliasInfo, BufferizationState &state)
Return true if the buffer to which operand would bufferize is equivalent to some buffer write.
static bool happensBefore (Operation *a, Operation *b, const DominanceInfo &domInfo)
Return true if a happens before b, i.e., a or one of its ancestors properly dominates b and b is not inside a.
static void annotateConflict (OpOperand *uRead, OpOperand *uConflictingWrite, Value lastWrite)
Annotate IR with details about the detected RaW conflict.
static bool hasReadAfterWriteInterference (const DenseSet< OpOperand *> &usesRead, const DenseSet< OpOperand *> &usesWrite, const DominanceInfo &domInfo, BufferizationState &state, const BufferizationAliasInfo &aliasInfo)
Given sets of uses and writes, return true if there is a RaW conflict under the assumption that all given reads/writes alias the same buffer and that all given writes bufferize inplace.
bool wouldCreateReadAfterWriteInterference (OpOperand &operand, OpResult result, const DominanceInfo &domInfo, BufferizationState &state, const BufferizationAliasInfo &aliasInfo, bool checkConsistencyOnly=false)
Return true if bufferizing result inplace would create a conflict.
static bool wouldCreateWriteToNonWritableBuffer (OpOperand &opOperand, OpResult opResult, const BufferizationAliasInfo &aliasInfo, BufferizationState &state)
Return true if bufferizing opOperand inplace with opResult would create a write to a non-writable buffer.
static LogicalResult bufferizableInPlaceAnalysisImpl (OpOperand &operand, OpResult result, BufferizationAliasInfo &aliasInfo, BufferizationState &state, const DominanceInfo &domInfo)
Determine if operand can be bufferized in-place with result.
static LogicalResult inPlaceAnalysis (SmallVector< Operation *> &ops, BufferizationAliasInfo &aliasInfo, BufferizationState &state, const DominanceInfo &domInfo, unsigned analysisFuzzerSeed=0)
Analyze the ops to determine which OpResults are inplaceable.
static LogicalResult inPlaceAnalysis (Operation *op, BufferizationAliasInfo &aliasInfo, BufferizationState &state, const DominanceInfo &domInfo, unsigned analysisFuzzerSeed=0)
Analyze all ops that are contained in op.
static void equivalenceAnalysis (SmallVector< Operation *> &ops, BufferizationAliasInfo &aliasInfo, BufferizationState &state)
Analyze equivalence of tied OpResult/OpOperand pairs of the given ops.
static void equivalenceAnalysis (Operation *op, BufferizationAliasInfo &aliasInfo, BufferizationState &state)
Analyze equivalence of tied OpResult/OpOperand pairs of all ops contained in op.
static LogicalResult checkAliasInfoConsistency (Operation *op, const DominanceInfo &domInfo, BufferizationState &state, const BufferizationAliasInfo &aliasInfo)
Assert that the current bufferization decisions are consistent.
static void annotateOpsWithBufferizationMarkers (Operation *op, const BufferizationAliasInfo &aliasInfo)
Annotate the IR with the result of the analysis. For testing/debugging only.
Variables
constexpr StringLiteral kInPlaceResultsAttrName = "__inplace_results_attr__"
Attribute marker to specify op results that can be bufferized inPlace.
Function Documentation
aliasesInPlaceWrite()
static bool aliasesInPlaceWrite (Value value, const BufferizationAliasInfo & aliasInfo, BufferizationState & state) static
Return true if the buffer to which operand would bufferize is equivalent to some buffer write.
Definition at line 212 of file ComprehensiveBufferize.cpp.
References mlir::Value::getUses(), and isInplaceMemoryWrite().
Referenced by wouldCreateWriteToNonWritableBuffer().
aliasesNonWritableBuffer()
static bool aliasesNonWritableBuffer (Value value, const BufferizationAliasInfo & aliasInfo, BufferizationState & state) static
Return true if, under current bufferization decisions, the buffer of value is not writable.
Definition at line 186 of file ComprehensiveBufferize.cpp.
References mlir::Value::dyn_cast().
Referenced by wouldCreateWriteToNonWritableBuffer().
annotateConflict()
static void annotateConflict (OpOperand * uRead, OpOperand * uConflictingWrite, Value lastWrite) static
Annotate IR with details about the detected RaW conflict.
Definition at line 243 of file ComprehensiveBufferize.cpp.
References mlir::Value::cast(), mlir::Value::dyn_cast(), mlir::Operation::getContext(), mlir::OpOperand::getOperandNumber(), mlir::detail::IROperandBase::getOwner(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), and mlir::Operation::setAttr().
Referenced by hasReadAfterWriteInterference().
annotateOpsWithBufferizationMarkers()
static void annotateOpsWithBufferizationMarkers (Operation * op, const BufferizationAliasInfo & aliasInfo) static
Annotate the IR with the result of the analysis. For testing/debugging only.
Definition at line 646 of file ComprehensiveBufferize.cpp.
References mlir::Operation::getResults(), setInPlaceOpResult(), and mlir::Operation::walk().
Referenced by mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
bufferizableInPlaceAnalysisImpl()
static LogicalResult bufferizableInPlaceAnalysisImpl (OpOperand & operand, OpResult result, BufferizationAliasInfo & aliasInfo, BufferizationState & state, const DominanceInfo & domInfo) static
Determine if operand can be bufferized in-place with result.
Definition at line 486 of file ComprehensiveBufferize.cpp.
References mlir::success(), wouldCreateReadAfterWriteInterference(), and wouldCreateWriteToNonWritableBuffer().
Referenced by inPlaceAnalysis().
checkAliasInfoConsistency()
static LogicalResult checkAliasInfoConsistency (Operation * op, const DominanceInfo & domInfo, BufferizationState & state, const BufferizationAliasInfo & aliasInfo) static
Assert that the current bufferization decisions are consistent.
Definition at line 610 of file ComprehensiveBufferize.cpp.
References mlir::WalkResult::advance(), mlir::Operation::emitError(), mlir::Operation::getOpOperands(), mlir::WalkResult::interrupt(), options, mlir::success(), mlir::Operation::walk(), mlir::WalkResult::wasInterrupted(), and wouldCreateReadAfterWriteInterference().
Referenced by mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
equivalenceAnalysis() [1/2]
static void equivalenceAnalysis (SmallVector< Operation *> & ops, BufferizationAliasInfo & aliasInfo, BufferizationState & state) static
Analyze equivalence of tied OpResult/OpOperand pairs of the given ops.
Definition at line 573 of file ComprehensiveBufferize.cpp.
Referenced by equivalenceAnalysis(), and mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
equivalenceAnalysis() [2/2]
static void equivalenceAnalysis (Operation * op, BufferizationAliasInfo & aliasInfo, BufferizationState & state) static
Analyze equivalence of tied OpResult/OpOperand pairs of all ops contained in op.
Definition at line 593 of file ComprehensiveBufferize.cpp.
References equivalenceAnalysis(), mlir::Operation::getResultTypes(), isaTensor(), mlir::PostOrder, and mlir::Operation::walk().
happensBefore()
static bool happensBefore (Operation * a, Operation * b, const DominanceInfo & domInfo) static
Return true if a happens before b, i.e., a or one of its ancestors properly dominates b and b is not inside a.
Definition at line 229 of file ComprehensiveBufferize.cpp.
References mlir::Operation::getParentOp(), mlir::Operation::isProperAncestor(), and mlir::DominanceInfo::properlyDominates().
Referenced by hasReadAfterWriteInterference().
hasReadAfterWriteInterference()
static bool hasReadAfterWriteInterference (const DenseSet< OpOperand *> & usesRead, const DenseSet< OpOperand *> & usesWrite, const DominanceInfo & domInfo, BufferizationState & state, const BufferizationAliasInfo & aliasInfo) static
Given sets of uses and writes, return true if there is a RaW conflict under the assumption that all given reads/writes alias the same buffer and that all given writes bufferize inplace.
A conflict is: According to SSA use-def chains, a read R is supposed to read the result of a write W1. But because of bufferization decisions, R actually reads another write W2.
Definition at line 282 of file ComprehensiveBufferize.cpp.
References annotateConflict(), mlir::Value::cast(), mlir::Value::getDefiningOp(), happensBefore(), mlir::insideMutuallyExclusiveRegions(), and options.
inPlaceAnalysis() [1/2]
static LogicalResult inPlaceAnalysis (SmallVector< Operation *> & ops, BufferizationAliasInfo & aliasInfo, BufferizationState & state, const DominanceInfo & domInfo, unsigned analysisFuzzerSeed = 0) static
Analyze the ops to determine which OpResults are inplaceable.
Walk ops in reverse and bufferize ops greedily. This is a good starter heuristic.
Even if an op does not read or write, it may still create an alias when bufferized in-place. An example of such ops is tensor.extract_slice.
Rationale for bufferizing %1 = tensor.extract_slice %0[...] inplace:
When bufferized out of place, an ExtractSliceOp lowers to alloc + copy. This cannot change the flow of information for either the source or the result buffers.
When bufferized inplace, an ExtractSliceOp does not by itself create any read or write from memory. Instead, it has the effect of merging the alias sets of the source and the result buffers.
An analysis is required to ensure inplace bufferization would not result in RaW dependence violations.
Definition at line 526 of file ComprehensiveBufferize.cpp.
References bufferizableInPlaceAnalysisImpl(), mlir::failed(), mlir::failure(), and mlir::success().
Referenced by inPlaceAnalysis(), and mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize().
inPlaceAnalysis() [2/2]
static LogicalResult inPlaceAnalysis (Operation * op, BufferizationAliasInfo & aliasInfo, BufferizationState & state, const DominanceInfo & domInfo, unsigned analysisFuzzerSeed = 0) static
Analyze all ops that are contained in op.
Definition at line 554 of file ComprehensiveBufferize.cpp.
References mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), inPlaceAnalysis(), isaTensor(), and mlir::Operation::walk().
isaTensor()
static bool isaTensor (Type t) static
Definition at line 126 of file ComprehensiveBufferize.cpp.
References mlir::Type::isa().
Referenced by mlir::linalg::comprehensive_bufferize::bufferize(), mlir::linalg::comprehensive_bufferize::AllocationHoistingBarrierOnly< OpTy >::bufferize(), equivalenceAnalysis(), and inPlaceAnalysis().
isInplaceMemoryWrite()
static bool isInplaceMemoryWrite (OpOperand & opOperand, const BufferizationAliasInfo & aliasInfo, BufferizationState & state) static
Return true if opOperand has been decided to bufferize in-place.
Definition at line 164 of file ComprehensiveBufferize.cpp.
References mlir::detail::IROperandBase::getOwner().
Referenced by aliasesInPlaceWrite().
setInPlaceOpResult()
static void setInPlaceOpResult (OpResult opResult, bool inPlace) static
Mark whether OpResult can actually be bufferized inplace.
If inPlace is true, the use-def chain analysis has guaranteed that no subsequent write would occur to the bufferized tensor value (i.e. the result can be bufferized inplace).
Definition at line 143 of file ComprehensiveBufferize.cpp.
References mlir::Attribute::dyn_cast_or_null(), mlir::Operation::getAttr(), mlir::Operation::getNumResults(), mlir::OpResult::getOwner(), mlir::OpResult::getResultNumber(), kInPlaceResultsAttrName, and mlir::Operation::setAttr().
Referenced by annotateOpsWithBufferizationMarkers().
wouldCreateReadAfterWriteInterference()
bool wouldCreateReadAfterWriteInterference (OpOperand & operand, OpResult result, const DominanceInfo & domInfo, BufferizationState & state, const BufferizationAliasInfo & aliasInfo, bool checkConsistencyOnly = false)
Return true if bufferizing result inplace would create a conflict.
A read R and a write W of the same alias set is a conflict if inplace bufferization of W changes the value read by R to a value different from the one that would be expected by tracing back R's origin through SSA use-def chains. A conflict can only be introduced by a new alias and/or an inplace bufferization decision.
Example: %0 = tensor.extract_slice t[...][...][1, 1] {inplace?} %1 = vector.transfer_write v1, t {inplace} : vector<5xf32>, tensor<?xf32> e = tensor.extract_slice %1 %2 = vector.transfer_write v2, %0 {inplace} : vector<6xf32>, tensor<?xf32> %3 = vector.transfer_read e, cst : tensor<?xf32>, vector<7xf32>
In the above example, the two TransferWriteOps have already been decided to bufferize inplace. Bufferizing the ExtractSliceOp inplace would create a conflict because:
According to SSA use-def chains, we expect to read the result of %1.
However, adding an alias {%0, t} would mean that the second TransferWriteOp overwrites the first one. Therefore, the TransferReadOp would no longer be reading the result of %1.
If checkConsistencyOnly is true, this function checks if there is a read-after-write conflict without bufferizing operand inplace. This would indicate a problem with the current inplace bufferization decisions.
Note: If checkConsistencyOnly, this function may be called with a null OpResult. In that case, only the consistency of bufferization decisions involving aliases of the given OpOperand are checked.
Definition at line 401 of file ComprehensiveBufferize.cpp.
Referenced by bufferizableInPlaceAnalysisImpl(), and checkAliasInfoConsistency().
wouldCreateWriteToNonWritableBuffer()
static bool wouldCreateWriteToNonWritableBuffer (OpOperand & opOperand, OpResult opResult, const BufferizationAliasInfo & aliasInfo, BufferizationState & state) static
Return true if bufferizing opOperand inplace with opResult would create a write to a non-writable buffer.
Definition at line 454 of file ComprehensiveBufferize.cpp.
References aliasesInPlaceWrite(), aliasesNonWritableBuffer(), and mlir::IROperand< DerivedT, IRValueT >::get().
Referenced by bufferizableInPlaceAnalysisImpl().
Variable Documentation
kInPlaceResultsAttrName
constexpr StringLiteral kInPlaceResultsAttrName = "__inplace_results_attr__"
Attribute marker to specify op results that can be bufferized inPlace.
Definition at line 137 of file ComprehensiveBufferize.cpp.
Referenced by setInPlaceOpResult().