MLIR: lib/Dialect/Affine/Utils/Utils.cpp File Reference
Utils.cpp File Reference
#include "mlir/Dialect/Affine/Utils.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Dominance.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/LoopUtils.h"
Functions
static void promoteIfBlock (AffineIfOp ifOp, bool elseBlock)
Promotes the then or the else block of ifOp (depending on whether elseBlock is false or true) into ifOp's containing block, and discards the rest of the op.
static Operation * getOutermostInvariantForOp (AffineIfOp ifOp)
Returns the outermost affine.for/parallel op that the ifOp is invariant on.
static AffineIfOp hoistAffineIfOp (AffineIfOp ifOp, Operation *hoistOverOp)
A helper for the mechanics of mlir::hoistAffineIfOp.
template<typename EffectType , typename T >
static bool hasNoInterveningEffect (Operation *start, T memOp)
Ensure that all operations that could be executed after start (noninclusive) and prior to memOp (e.g.
static LogicalResult forwardStoreToLoad (AffineReadOpInterface loadOp, SmallVectorImpl< Operation *> &loadOpsToErase, SmallPtrSetImpl< Value > &memrefsToErase, DominanceInfo &domInfo)
Attempt to eliminate loadOp by replacing it with a value stored into memory which the load is guaranteed to retrieve.
static void findUnusedStore (AffineWriteOpInterface writeA, SmallVectorImpl< Operation *> &opsToErase, SmallPtrSetImpl< Value > &memrefsToErase, PostDominanceInfo &postDominanceInfo)
static void loadCSE (AffineReadOpInterface loadA, SmallVectorImpl< Operation *> &loadOpsToErase, DominanceInfo &domInfo)
Function Documentation
findUnusedStore()
static void findUnusedStore (AffineWriteOpInterface writeA, SmallVectorImpl< Operation *> & opsToErase, SmallPtrSetImpl< Value > & memrefsToErase, PostDominanceInfo & postDominanceInfo) static
Definition at line 684 of file Utils.cpp.
References mlir::AffineWriteOpInterface::getMemRef(), mlir::Value::getUsers(), and mlir::PostDominanceInfo::postDominates().
Referenced by mlir::affineScalarReplace().
forwardStoreToLoad()
static LogicalResult forwardStoreToLoad (AffineReadOpInterface loadOp, SmallVectorImpl< Operation *> & loadOpsToErase, SmallPtrSetImpl< Value > & memrefsToErase, DominanceInfo & domInfo) static
Attempt to eliminate loadOp by replacing it with a value stored into memory which the load is guaranteed to retrieve.
This check involves three components: 1) The store and load must be on the same location 2) The store must dominate (and therefore must always occur prior to) the load 3) No other operations will overwrite the memory loaded between the given load and store. If such a value exists, the replaced loadOp will be added to loadOpsToErase and its memref will be added to memrefsToErase.
Definition at line 620 of file Utils.cpp.
References mlir::DominanceInfo::dominates(), mlir::failure(), mlir::AffineReadOpInterface::getMemRef(), mlir::Value::getType(), mlir::Value::getUsers(), mlir::AffineReadOpInterface::getValue(), mlir::Value::replaceAllUsesWith(), and mlir::success().
Referenced by mlir::affineScalarReplace().
getOutermostInvariantForOp()
static Operation* getOutermostInvariantForOp (AffineIfOp ifOp) static
Returns the outermost affine.for/parallel op that the ifOp is invariant on.
The ifOp could be hoisted and placed right before such an operation. This method assumes that the ifOp has been canonicalized (to be correct and effective).
Definition at line 47 of file Utils.cpp.
References mlir::Operation::getOperands().
Referenced by mlir::hoistAffineIfOp().
hasNoInterveningEffect()
template<typename EffectType , typename T > static bool hasNoInterveningEffect (Operation * start, T memOp) static
Ensure that all operations that could be executed after start (noninclusive) and prior to memOp (e.g.
on a control flow/op path between the operations) do not have the potential memory effect EffectType on memOp. memOp is an operation that reads or writes to a memref. For example, if EffectType is MemoryEffects::Write, this method will check if there is no write to the memory between start and memOp that would change the read within memOp.
Definition at line 445 of file Utils.cpp.
References mlir::checkMemrefAccessDependence(), mlir::Block::end(), mlir::Operation::getBlock(), mlir::Value::getDefiningOp(), mlir::getNumCommonSurroundingLoops(), mlir::Operation::getParentOp(), mlir::Operation::getParentRegion(), mlir::Region::getParentRegion(), mlir::Block::getSuccessors(), mlir::hasDependence(), mlir::Operation::isAncestor(), mlir::Region::isAncestor(), and mlir::MemRefAccess::memref.
hoistAffineIfOp()
static AffineIfOp hoistAffineIfOp (AffineIfOp ifOp, Operation * hoistOverOp) static
A helper for the mechanics of mlir::hoistAffineIfOp.
Hoists ifOp just over hoistOverOp. Returns the new hoisted op if any hoisting happened, otherwise the same ifOp.
Definition at line 73 of file Utils.cpp.
References mlir::WalkResult::advance(), mlir::BlockAndValueMapping::clear(), mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::Operation::getBlock(), mlir::Builder::getBoolAttr(), mlir::Block::getOperations(), mlir::Builder::getStringAttr(), mlir::WalkResult::interrupt(), promoteIfBlock(), and mlir::OpBuilder::setInsertionPointAfter().
loadCSE()
static void loadCSE (AffineReadOpInterface loadA, SmallVectorImpl< Operation *> & loadOpsToErase, DominanceInfo & domInfo) static
Definition at line 730 of file Utils.cpp.
References mlir::DominanceInfo::dominates(), mlir::AffineReadOpInterface::getMemRef(), mlir::OpState::getOperation(), mlir::Value::getType(), mlir::Value::getUsers(), mlir::AffineReadOpInterface::getValue(), and mlir::Value::replaceAllUsesWith().
Referenced by mlir::affineScalarReplace().
promoteIfBlock()
static void promoteIfBlock (AffineIfOp ifOp, bool elseBlock) static
Promotes the then or the else block of ifOp (depending on whether elseBlock is false or true) into ifOp's containing block, and discards the rest of the op.
Definition at line 31 of file Utils.cpp.
References mlir::Block::begin(), mlir::Block::end(), and mlir::Block::getOperations().
Referenced by hoistAffineIfOp().