MLIR: mlir::linalg::comprehensive_bufferize Namespace Reference
mlir::linalg::comprehensive_bufferize Namespace Reference
Namespaces
affine_ext
arith_ext
bufferization_ext
linalg_ext
scf_ext
std_ext
tensor_ext
vector_ext
Classes
struct AllocationCallbacks
Callback functions that are used to allocate/deallocate/copy memory buffers.
struct AllocationHoistingBarrierOnly
AllocationHoistingBarrierOnly is an external implementation of BufferizableOpInterface for ops that are (not yet) bufferizable, but are known to be allocation hoisting barriers.
class BufferizationAliasInfo
The BufferizationAliasInfo class maintains a list of buffer aliases and equivalence classes to support bufferization.
struct BufferizationOptions
Options for ComprehensiveBufferize.
class BufferizationState
BufferizationState provides a variety of helper functions for dealing with tensor values and memref buffers.
struct DialectBufferizationState
Dialect-specific bufferization state.
struct PostAnalysisStep
PostAnalysisSteps can be registered with BufferizationOptions and are executed after the analysis, but before bufferization.
Typedefs
using PostAnalysisStepList = std::vector< std::unique_ptr< PostAnalysisStep > >
Enumerations
enum BufferRelation { BufferRelation::None, BufferRelation::Equivalent }
Specify fine-grain relationship between buffers to enable more analysis.
Functions
std::unique_ptr< AllocationCallbacks > defaultAllocationCallbacks ()
Return default allocation callbacks.
bool isFunctionArgument (Value value)
Return true if the given value is a BlockArgument of a FuncOp.
LogicalResult bufferize (Region *region, BufferizationState &state)
Bufferize all ops in the given region.
LogicalResult bufferize (Block *block, BufferizationState &state)
Bufferize all ops in the given block.
LogicalResult bufferize (Operation *op, BufferizationState &state)
Bufferize the given op.
MemRefType getContiguousMemRefType (ShapedType shapedType, MemRefLayoutAttrInterface layout={}, Attribute memorySpace={})
Return a contiguous MemRefType (i.e.
Type getContiguousOrUnrankedMemRefType (Type type, MemRefLayoutAttrInterface layout={}, Attribute memorySpace={})
Return a contiguous MemRefType (i.e.
MemRefType getDynamicMemRefType (RankedTensorType tensorType, unsigned addressSpace=0)
Return a MemRefType to which the tensorType can be bufferized in a composable fashion.
LogicalResult runComprehensiveBufferize (Operation *op, const BufferizationOptions &options, BufferizationState &state, const std::vector< std::unique_ptr< PostAnalysisStep >> &extraSteps)
Bufferize the given operation. Reuses an existing BufferizationState object.
LogicalResult runComprehensiveBufferize (Operation *op, const BufferizationOptions &options)
Bufferize the given operation.
LogicalResult runComprehensiveBufferize (ModuleOp moduleOp, const BufferizationOptions &options)
Bufferize the given module.
Variables
static constexpr int64_t kBufferAlignments = 128
Typedef Documentation
PostAnalysisStepList
using mlir::linalg::comprehensive_bufferize::PostAnalysisStepList = typedef std::vector<std::unique_ptr<PostAnalysisStep> >
Definition at line 79 of file BufferizableOpInterface.h.
Enumeration Type Documentation
BufferRelation
enum mlir::linalg::comprehensive_bufferize::BufferRelation strong
Specify fine-grain relationship between buffers to enable more analysis.
Enumerator
None
Equivalent
Definition at line 171 of file BufferizableOpInterface.h.
Function Documentation
bufferize() [1/3]
LogicalResult mlir::linalg::comprehensive_bufferize::bufferize (Region * region, BufferizationState & state)
Bufferize all ops in the given region.
Definition at line 458 of file BufferizableOpInterface.cpp.
References mlir::failed(), mlir::failure(), and mlir::success().
Referenced by mlir::linalg::comprehensive_bufferize::scf_ext::ExecuteRegionOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::scf_ext::IfOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferize(), bufferize(), mlir::linalg::comprehensive_bufferize::AllocationHoistingBarrierOnly< OpTy >::bufferize(), mlir::linalg::comprehensive_bufferize::std_ext::FuncOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::BufferizationState::getBuilder(), and runComprehensiveBufferize().
bufferize() [2/3]
LogicalResult mlir::linalg::comprehensive_bufferize::bufferize (Block * block, BufferizationState & state)
Bufferize all ops in the given block.
Definition at line 467 of file BufferizableOpInterface.cpp.
References bufferize(), mlir::failed(), mlir::failure(), mlir::Block::getOperations(), and mlir::success().
bufferize() [3/3]
LogicalResult mlir::linalg::comprehensive_bufferize::bufferize (Operation * op, BufferizationState & state)
Bufferize the given op.
If the op has no tensor OpOperands/OpResults, this function returns immediately. Otherwise, it calls the bufferize interface method of BufferizableOpInterface.
Definition at line 482 of file BufferizableOpInterface.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationOptions::allowUnknownOps, bufferize(), mlir::linalg::comprehensive_bufferize::BufferizationOptions::dynCastBufferizableOp(), mlir::Operation::emitError(), mlir::failed(), mlir::failure(), mlir::linalg::comprehensive_bufferize::BufferizationState::getBuilder(), mlir::Operation::getOperandTypes(), mlir::linalg::comprehensive_bufferize::BufferizationState::getOptions(), mlir::Operation::getRegions(), mlir::Operation::getResultTypes(), isaTensor(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
defaultAllocationCallbacks()
std::unique_ptr< AllocationCallbacks > mlir::linalg::comprehensive_bufferize::defaultAllocationCallbacks ()
Return default allocation callbacks.
Definition at line 67 of file BufferizableOpInterface.cpp.
References defaultAllocationFn(), defaultDeallocationFn(), and defaultMemCpyFn().
getContiguousMemRefType()
MemRefType mlir::linalg::comprehensive_bufferize::getContiguousMemRefType (ShapedType shapedType, MemRefLayoutAttrInterface layout = {}, Attribute memorySpace = {})
Return a contiguous MemRefType (i.e.
with canonical/empty layout map) with the same shape as shapedType and specified layout and addressSpace.
Definition at line 695 of file BufferizableOpInterface.cpp.
References mlir::ShapedType::getElementType(), and mlir::ShapedType::getShape().
Referenced by getAllocationTypeAndShape(), mlir::linalg::comprehensive_bufferize::BufferizationState::getBuilder(), and getContiguousOrUnrankedMemRefType().
getContiguousOrUnrankedMemRefType()
Type mlir::linalg::comprehensive_bufferize::getContiguousOrUnrankedMemRefType (Type type, MemRefLayoutAttrInterface layout = {}, Attribute memorySpace = {})
Return a contiguous MemRefType (i.e.
with canonical/empty layout map) with the same shape as shapedType and specified layout and addressSpace or an UnrankedMemRefType otherwise.
Definition at line 702 of file BufferizableOpInterface.cpp.
References mlir::Type::cast(), getContiguousMemRefType(), mlir::getElementTypeOrSelf(), and mlir::Type::isa().
Referenced by mlir::linalg::comprehensive_bufferize::tensor_ext::CastOpInterface::bufferize(), getBufferizedFunctionType(), and mlir::linalg::comprehensive_bufferize::BufferizationState::getBuilder().
getDynamicMemRefType()
MemRefType mlir::linalg::comprehensive_bufferize::getDynamicMemRefType (RankedTensorType tensorType, unsigned addressSpace = 0)
Return a MemRefType to which the tensorType can be bufferized in a composable fashion.
The layout must be the most dynamic possible and canonicalize away once bufferization is finished.
Definition at line 711 of file BufferizableOpInterface.cpp.
References mlir::ShapedType::kDynamicStrideOrOffset, and mlir::makeStridedLinearLayoutMap().
Referenced by mlir::linalg::comprehensive_bufferize::scf_ext::IfOpInterface::bufferize(), getBufferizedFunctionType(), mlir::linalg::comprehensive_bufferize::BufferizationState::getBuilder(), and mlir::linalg::comprehensive_bufferize::BufferizationState::lookupBuffer().
isFunctionArgument()
bool mlir::linalg::comprehensive_bufferize::isFunctionArgument (Value value)
Return true if the given value is a BlockArgument of a FuncOp.
Definition at line 650 of file BufferizableOpInterface.cpp.
References mlir::Value::dyn_cast().
Referenced by mlir::linalg::comprehensive_bufferize::bufferization_ext::ToMemrefOpInterface::bufferize(), and mlir::linalg::comprehensive_bufferize::BufferizationState::lookupBuffer().
runComprehensiveBufferize() [1/3]
LogicalResult mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize (Operation * op, const BufferizationOptions & options, BufferizationState & state, const std::vector< std::unique_ptr< PostAnalysisStep >> & extraSteps)
Bufferize the given operation. Reuses an existing BufferizationState object.
Referenced by allocationFnUsingAlloca(), mlir::linalg::comprehensive_bufferize::BufferizationState::getBuilder(), and runComprehensiveBufferize().
runComprehensiveBufferize() [2/3]
LogicalResult mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize (ModuleOp moduleOp, const BufferizationOptions & options)
Bufferize the given module.
This bufferizations performs a simple function call analysis to determine which function arguments are inplaceable.
Definition at line 726 of file ModuleBufferization.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationOptions::allowReturnMemref, annotateOpsWithBufferizationMarkers(), bufferizeFuncOpBoundary(), equivalenceAnalysis(), mlir::failed(), mlir::failure(), getFuncOpsOrderedByCalls(), getModuleBufferizationState(), layoutPostProcessing(), removeBufferizationFuncArguments(), runComprehensiveBufferize(), mlir::success(), and mlir::linalg::comprehensive_bufferize::BufferizationOptions::testAnalysisOnly.
runComprehensiveBufferize() [3/3]
LogicalResult mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize (Operation * op, const BufferizationOptions & options)
Bufferize the given operation.
Definition at line 655 of file ComprehensiveBufferize.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationOptions::analysisFuzzerSeed, annotateOpsWithBufferizationMarkers(), bufferize(), checkAliasInfoConsistency(), equivalenceAnalysis(), mlir::failed(), mlir::failure(), inPlaceAnalysis(), options, mlir::linalg::comprehensive_bufferize::BufferizationOptions::postAnalysisSteps, runComprehensiveBufferize(), mlir::success(), and mlir::linalg::comprehensive_bufferize::BufferizationOptions::testAnalysisOnly.
Variable Documentation
kBufferAlignments
constexpr int64_t mlir::linalg::comprehensive_bufferize::kBufferAlignments = 128 static
Definition at line 30 of file BufferizableOpInterface.h.
Referenced by allocationFnUsingAlloca(), and defaultAllocationFn().