MLIR: mlir::presburger_utils Namespace Reference
mlir::presburger_utils Namespace Reference
Functions
Optional< std::pair< unsigned, unsigned > > computeSingleVarRepr (const IntegerPolyhedron &cst, ArrayRef< bool > foundRepr, unsigned pos, SmallVector< int64_t, 8 > &dividend, unsigned &divisor)
Check if the pos^th identifier can be expressed as a floordiv of an affine function of other identifiers (where the divisor is a positive constant).
Function Documentation
computeSingleVarRepr()
Optional< std::pair< unsigned, unsigned > > mlir::presburger_utils::computeSingleVarRepr (const IntegerPolyhedron & cst, ArrayRef< bool > foundRepr, unsigned pos, SmallVector< int64_t, 8 > & dividend, unsigned & divisor)
Check if the pos^th identifier can be expressed as a floordiv of an affine function of other identifiers (where the divisor is a positive constant).
foundRepr contains a boolean for each identifier indicating if the explicit representation for that identifier has already been computed. Returns the upper and lower bound inequalities using which the floordiv can be computed. If the representation could be computed, dividend and denominator are set. If the representation could not be computed, llvm::None is returned.
Definition at line 116 of file Utils.cpp.
References mlir::failed(), getDivRepr(), mlir::IntegerPolyhedron::getLowerAndUpperBoundIndices(), and mlir::IntegerPolyhedron::getNumIds().
Referenced by detectAsFloorDiv().