MLIR: mlir::linalg::comprehensive_bufferize::AllocationHoistingBarrierOnly< OpTy > Struct Template Reference
mlir::linalg::comprehensive_bufferize::AllocationHoistingBarrierOnly< OpTy > Struct Template Reference
AllocationHoistingBarrierOnly is an external implementation of BufferizableOpInterface for ops that are (not yet) bufferizable, but are known to be allocation hoisting barriers.
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.h"
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand, BufferizationState &state) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand, BufferizationState &state) const
SmallVector< OpOperand * > getAliasingOpOperand (Operation *op, OpResult opResult, BufferizationState &state) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand, BufferizationState &state) const
BufferRelation bufferRelation (Operation *op, OpResult opResult, const BufferizationAliasInfo &aliasInfo, BufferizationState &state) const
bool isWritable (Operation *op, Value value, BufferizationState &state) const
LogicalResult bufferize (Operation *op, OpBuilder &b, BufferizationState &state) const
bool isAllocationHoistingBarrier (Operation *op) const
Detailed Description
template<typename OpTy>
struct mlir::linalg::comprehensive_bufferize::AllocationHoistingBarrierOnly< OpTy >
AllocationHoistingBarrierOnly is an external implementation of BufferizableOpInterface for ops that are (not yet) bufferizable, but are known to be allocation hoisting barriers.
All interface methods (except for isAllocationHoistingBarrier) are implemented conservatively.
Definition at line 493 of file BufferizableOpInterface.h.
Member Function Documentation
bufferize()
template<typename OpTy > LogicalResult mlir::linalg::comprehensive_bufferize::AllocationHoistingBarrierOnly< OpTy >::bufferize (Operation * op, OpBuilder & b, BufferizationState & state) const inline
Definition at line 527 of file BufferizableOpInterface.h.
References mlir::linalg::comprehensive_bufferize::BufferizationOptions::allowUnknownOps, mlir::linalg::comprehensive_bufferize::bufferize(), mlir::Operation::emitError(), mlir::failed(), mlir::failure(), mlir::Operation::getOperandTypes(), mlir::linalg::comprehensive_bufferize::BufferizationState::getOptions(), mlir::Operation::getRegions(), mlir::Operation::getResultTypes(), isaTensor(), and mlir::success().
bufferizesToMemoryRead()
template<typename OpTy > bool mlir::linalg::comprehensive_bufferize::AllocationHoistingBarrierOnly< OpTy >::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 496 of file BufferizableOpInterface.h.
bufferizesToMemoryWrite()
template<typename OpTy > bool mlir::linalg::comprehensive_bufferize::AllocationHoistingBarrierOnly< OpTy >::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 501 of file BufferizableOpInterface.h.
bufferRelation()
template<typename OpTy > BufferRelation mlir::linalg::comprehensive_bufferize::AllocationHoistingBarrierOnly< OpTy >::bufferRelation (Operation * op, OpResult opResult, const BufferizationAliasInfo & aliasInfo, BufferizationState & state) const inline
Definition at line 517 of file BufferizableOpInterface.h.
References mlir::linalg::comprehensive_bufferize::None.
getAliasingOpOperand()
template<typename OpTy > SmallVector<OpOperand *> mlir::linalg::comprehensive_bufferize::AllocationHoistingBarrierOnly< OpTy >::getAliasingOpOperand (Operation * op, OpResult opResult, BufferizationState & state) const inline
Definition at line 507 of file BufferizableOpInterface.h.
getAliasingOpResult()
template<typename OpTy > OpResult mlir::linalg::comprehensive_bufferize::AllocationHoistingBarrierOnly< OpTy >::getAliasingOpResult (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 512 of file BufferizableOpInterface.h.
isAllocationHoistingBarrier()
template<typename OpTy > bool mlir::linalg::comprehensive_bufferize::AllocationHoistingBarrierOnly< OpTy >::isAllocationHoistingBarrier (Operation * op) const inline
Definition at line 542 of file BufferizableOpInterface.h.
isWritable()
template<typename OpTy > bool mlir::linalg::comprehensive_bufferize::AllocationHoistingBarrierOnly< OpTy >::isWritable (Operation * op, Value value, BufferizationState & state) const inline
Definition at line 523 of file BufferizableOpInterface.h.
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Linalg/ComprehensiveBufferize/BufferizableOpInterface.h