MLIR: mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface Struct Reference
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand, BufferizationState &state) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand, BufferizationState &state) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand, BufferizationState &state) const
BufferRelation bufferRelation (Operation *op, OpResult opResult, const BufferizationAliasInfo &aliasInfo, BufferizationState &state) const
bool isWritable (Operation *op, Value value, BufferizationState &state) const
LogicalResult bufferize (Operation *op, OpBuilder &, BufferizationState &state) const
Detailed Description
Definition at line 228 of file SCFInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferize (Operation * op, OpBuilder & , BufferizationState & state) const inline
Definition at line 279 of file SCFInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::bufferize(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::Block::front(), mlir::Operation::getContext(), mlir::Value::getLoc(), mlir::linalg::comprehensive_bufferize::BufferizationState::getResultBuffer(), mlir::Operation::getResults(), mlir::linalg::comprehensive_bufferize::BufferizationState::replaceOp(), mlir::linalg::comprehensive_bufferize::scf_ext::AssertDestinationPassingStyle::run(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 231 of file SCFInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationState::isValueRead().
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 239 of file SCFInterfaceImpl.cpp.
bufferRelation()
BufferRelation mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferRelation (Operation * op, OpResult opResult, const BufferizationAliasInfo & aliasInfo, BufferizationState & state) const inline
Definition at line 255 of file SCFInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::areEquivalentBufferizedValues(), mlir::linalg::comprehensive_bufferize::Equivalent, mlir::OpResult::getResultNumber(), and mlir::linalg::comprehensive_bufferize::None.
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 247 of file SCFInterfaceImpl.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getType(), and mlir::Type::isa().
isWritable()
bool mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::isWritable (Operation * op, Value value, BufferizationState & state) const inline
Definition at line 269 of file SCFInterfaceImpl.cpp.
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/SCFInterfaceImpl.cpp