MLIR: mlir::linalg::comprehensive_bufferize::tensor_ext::InsertOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::tensor_ext::InsertOpInterface Struct Reference
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand, BufferizationState &state) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand, BufferizationState &state) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand, BufferizationState &state) const
SmallVector< OpOperand * > getAliasingOpOperand (Operation *op, OpResult opResult, BufferizationState &state) const
LogicalResult bufferize (Operation *op, OpBuilder &b, BufferizationState &state) const
BufferRelation bufferRelation (Operation *op, OpResult opResult, const BufferizationAliasInfo &aliasInfo, BufferizationState &state) const
Detailed Description
Definition at line 212 of file TensorInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::tensor_ext::InsertOpInterface::bufferize (Operation * op, OpBuilder & b, BufferizationState & state) const inline
Definition at line 238 of file TensorInterfaceImpl.cpp.
References mlir::OpBuilder::create(), mlir::linalg::comprehensive_bufferize::BufferizationState::getResultBuffer(), mlir::linalg::comprehensive_bufferize::BufferizationState::replaceOp(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::tensor_ext::InsertOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 215 of file TensorInterfaceImpl.cpp.
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::tensor_ext::InsertOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 220 of file TensorInterfaceImpl.cpp.
bufferRelation()
BufferRelation mlir::linalg::comprehensive_bufferize::tensor_ext::InsertOpInterface::bufferRelation (Operation * op, OpResult opResult, const BufferizationAliasInfo & aliasInfo, BufferizationState & state) const inline
Definition at line 249 of file TensorInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::Equivalent.
getAliasingOpOperand()
SmallVector<OpOperand *> mlir::linalg::comprehensive_bufferize::tensor_ext::InsertOpInterface::getAliasingOpOperand (Operation * op, OpResult opResult, BufferizationState & state) const inline
Definition at line 233 of file TensorInterfaceImpl.cpp.
References mlir::Operation::getOpOperand().
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::tensor_ext::InsertOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 225 of file TensorInterfaceImpl.cpp.
References mlir::Operation::getOpOperand(), and mlir::Operation::getOpResult().
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/TensorInterfaceImpl.cpp