MLIR: mlir::linalg::comprehensive_bufferize::tensor_ext::CastOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::tensor_ext::CastOpInterface Struct Reference
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand, BufferizationState &state) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand, BufferizationState &state) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand, BufferizationState &state) const
BufferRelation bufferRelation (Operation *op, OpResult opResult, const BufferizationAliasInfo &aliasInfo, BufferizationState &state) const
LogicalResult bufferize (Operation *op, OpBuilder &b, BufferizationState &state) const
Detailed Description
Definition at line 40 of file TensorInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::tensor_ext::CastOpInterface::bufferize (Operation * op, OpBuilder & b, BufferizationState & state) const inline
Definition at line 64 of file TensorInterfaceImpl.cpp.
References mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::failure(), mlir::linalg::comprehensive_bufferize::getContiguousOrUnrankedMemRefType(), mlir::linalg::comprehensive_bufferize::BufferizationState::getResultBuffer(), mlir::Type::isa(), mlir::linalg::comprehensive_bufferize::BufferizationState::replaceOpWithNewOp(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::tensor_ext::CastOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 43 of file TensorInterfaceImpl.cpp.
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::tensor_ext::CastOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 48 of file TensorInterfaceImpl.cpp.
bufferRelation()
BufferRelation mlir::linalg::comprehensive_bufferize::tensor_ext::CastOpInterface::bufferRelation (Operation * op, OpResult opResult, const BufferizationAliasInfo & aliasInfo, BufferizationState & state) const inline
Definition at line 58 of file TensorInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::Equivalent.
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::tensor_ext::CastOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 53 of file TensorInterfaceImpl.cpp.
References mlir::Operation::getResult().
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/TensorInterfaceImpl.cpp