MLIR: mlir::linalg::comprehensive_bufferize::scf_ext::AssertDestinationPassingStyle Struct Reference
mlir::linalg::comprehensive_bufferize::scf_ext::AssertDestinationPassingStyle Struct Reference
Equivalence analysis for scf.for.
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/SCFInterfaceImpl.h"
Public Member Functions
LogicalResult run (Operation *op, BufferizationState &state, BufferizationAliasInfo &aliasInfo, SmallVector< Operation *> &newOps) override
Run the post analysis step.
Public Member Functions inherited from mlir::linalg::comprehensive_bufferize::PostAnalysisStep
virtual ~PostAnalysisStep ()
Detailed Description
Equivalence analysis for scf.for.
Raise an error if iter_args are not equivalent to their corresponding loop yield values.
Definition at line 24 of file SCFInterfaceImpl.h.
Member Function Documentation
run()
LogicalResult mlir::linalg::comprehensive_bufferize::scf_ext::AssertDestinationPassingStyle::run (Operation * op, BufferizationState & state, BufferizationAliasInfo & aliasInfo, SmallVector< Operation *> & newOps) override virtual
Run the post analysis step.
This function may modify the IR, but must keep aliasInfo (inside state) consistent. Newly created operations and operations that should be re-analyzed must be stored in newOps.
Implements mlir::linalg::comprehensive_bufferize::PostAnalysisStep.
Definition at line 360 of file SCFInterfaceImpl.cpp.
References mlir::WalkResult::advance(), mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::applyOnEquivalenceClass(), mlir::linalg::comprehensive_bufferize::BufferizationAliasInfo::areEquivalentBufferizedValues(), mlir::WalkResult::interrupt(), mlir::success(), value, and mlir::Operation::walk().
Referenced by mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferize().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Linalg/ComprehensiveBufferize/SCFInterfaceImpl.h
lib/Dialect/Linalg/ComprehensiveBufferize/SCFInterfaceImpl.cpp