MLIR: mlir::linalg::comprehensive_bufferize::tensor_ext::DimOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::tensor_ext::DimOpInterface Struct Reference
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand, BufferizationState &state) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand, BufferizationState &state) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand, BufferizationState &state) const
LogicalResult bufferize (Operation *op, OpBuilder &b, BufferizationState &state) const
Detailed Description
Definition at line 90 of file TensorInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::tensor_ext::DimOpInterface::bufferize (Operation * op, OpBuilder & b, BufferizationState & state) const inline
Definition at line 108 of file TensorInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::BufferizationState::lookupBuffer(), mlir::linalg::comprehensive_bufferize::BufferizationState::replaceOpWithNewOp(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::tensor_ext::DimOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 93 of file TensorInterfaceImpl.cpp.
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::tensor_ext::DimOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 98 of file TensorInterfaceImpl.cpp.
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::tensor_ext::DimOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 103 of file TensorInterfaceImpl.cpp.
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/TensorInterfaceImpl.cpp