MLIR: mlir::linalg::comprehensive_bufferize::scf_ext::ExecuteRegionOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::scf_ext::ExecuteRegionOpInterface Struct Reference
Public Member Functions
SmallVector< OpOperand * > getAliasingOpOperand (Operation *op, OpResult opResult, BufferizationState &state) const
bool mustBufferizeInPlace (Operation *op, OpResult opResult, BufferizationState &state) const
bool isMemoryWrite (Operation *op, OpResult opResult, BufferizationState &state) const
LogicalResult bufferize (Operation *op, OpBuilder &b, BufferizationState &state) const
BufferRelation bufferRelation (Operation *op, OpResult opResult, const BufferizationAliasInfo &aliasInfo, BufferizationState &state) const
Detailed Description
Definition at line 22 of file SCFInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::scf_ext::ExecuteRegionOpInterface::bufferize (Operation * op, OpBuilder & b, BufferizationState & state) const inline
Definition at line 63 of file SCFInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::bufferize(), mlir::Operation::emitError(), and mlir::Operation::getResultTypes().
bufferRelation()
BufferRelation mlir::linalg::comprehensive_bufferize::scf_ext::ExecuteRegionOpInterface::bufferRelation (Operation * op, OpResult opResult, const BufferizationAliasInfo & aliasInfo, BufferizationState & state) const inline
Definition at line 77 of file SCFInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::Equivalent.
getAliasingOpOperand()
SmallVector<OpOperand *> mlir::linalg::comprehensive_bufferize::scf_ext::ExecuteRegionOpInterface::getAliasingOpOperand (Operation * op, OpResult opResult, BufferizationState & state) const inline
Definition at line 26 of file SCFInterfaceImpl.cpp.
References mlir::Operation::getOpResults().
isMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::scf_ext::ExecuteRegionOpInterface::isMemoryWrite (Operation * op, OpResult opResult, BufferizationState & state) const inline
Definition at line 53 of file SCFInterfaceImpl.cpp.
mustBufferizeInPlace()
bool mlir::linalg::comprehensive_bufferize::scf_ext::ExecuteRegionOpInterface::mustBufferizeInPlace (Operation * op, OpResult opResult, BufferizationState & state) const inline
Definition at line 43 of file SCFInterfaceImpl.cpp.
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/SCFInterfaceImpl.cpp