MLIR: mlir::linalg::comprehensive_bufferize::std_ext::ReturnOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::std_ext::ReturnOpInterface Struct Reference
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand, BufferizationState &state) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand, BufferizationState &state) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand, BufferizationState &state) const
LogicalResult bufferize (Operation *op, OpBuilder &b, BufferizationState &state) const
Detailed Description
Definition at line 620 of file ModuleBufferization.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::std_ext::ReturnOpInterface::bufferize (Operation * op, OpBuilder & b, BufferizationState & state) const inline
Definition at line 638 of file ModuleBufferization.cpp.
References mlir::OpBuilder::create(), mlir::linalg::comprehensive_bufferize::BufferizationState::lookupBuffer(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::std_ext::ReturnOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 623 of file ModuleBufferization.cpp.
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::std_ext::ReturnOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 628 of file ModuleBufferization.cpp.
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::std_ext::ReturnOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand, BufferizationState & state) const inline
Definition at line 633 of file ModuleBufferization.cpp.
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/ModuleBufferization.cpp