MLIR: lib/Conversion/TosaToLinalg/TosaToLinalgNamed.cpp File Reference
TosaToLinalgNamed.cpp File Reference
#include "mlir/Conversion/TosaToLinalg/TosaToLinalg.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Tosa/IR/TosaOps.h"
#include "mlir/Dialect/Utils/ReshapeOpsUtils.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include <numeric>
Functions
static SmallVector< StringRef > getNParallelLoopsAttrs (unsigned nParallelLoops)
template<typename T >
static void getValuesFromIntArrayAttribute (ArrayAttr attr, SmallVector< T > &arrayValues)
template<typename T , typename P >
static mlir::SelectOp clampHelper (Location loc, Value arg, arith::ConstantOp min, arith::ConstantOp max, P pred, OpBuilder &rewriter)
static mlir::Value applyPad (Location loc, Value input, ArrayRef< int64_t > pad, Attribute padAttr, OpBuilder &rewriter)
static SmallVector< Value > filterDynamicDims (SmallVector< Value > dynDims)
Function Documentation
applyPad()
static mlir::Value applyPad (Location loc, Value input, ArrayRef< int64_t > pad, Attribute padAttr, OpBuilder & rewriter) static
Definition at line 54 of file TosaToLinalgNamed.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::ShapedType::getElementType(), mlir::Builder::getIndexAttr(), mlir::ShapedType::getShape(), and mlir::Value::getType().
Referenced by filterDynamicDims().
clampHelper()
template<typename T , typename P > static mlir::SelectOp clampHelper (Location loc, Value arg, arith::ConstantOp min, arith::ConstantOp max, P pred, OpBuilder & rewriter) static
Definition at line 44 of file TosaToLinalgNamed.cpp.
References mlir::OpBuilder::create(), max(), and min().
filterDynamicDims()
static SmallVector<Value> filterDynamicDims (SmallVector< Value > dynDims) static
Definition at line 85 of file TosaToLinalgNamed.cpp.
References applyPad(), mlir::Attribute::cast(), mlir::Location::cast(), mlir::Type::cast(), clamp(), mlir::ShapedType::clone(), mlir::OpBuilder::create(), mlir::failure(), mlir::AffineMap::get(), mlir::DenseIntElementsAttr::get(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getBoolAttr(), mlir::Builder::getContext(), mlir::ShapedType::getElementType(), getElementType(), mlir::Builder::getFloatAttr(), mlir::FloatType::getFloatSemantics(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI32Type(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getI64Type(), mlir::Builder::getI64VectorAttr(), mlir::Builder::getI8IntegerAttr(), mlir::Builder::getIntegerAttr(), mlir::Builder::getMultiDimIdentityMap(), getNParallelLoopsAttrs(), mlir::ShapedType::getRank(), mlir::ShapedType::getShape(), mlir::Value::getType(), getValuesFromIntArrayAttribute(), mlir::Builder::getZeroAttr(), mlir::ShapedType::hasRank(), mlir::ShapedType::hasStaticShape(), mlir::Type::isa(), mlir::ShapedType::isDynamicDim(), max(), min(), mlir::ConversionPatternRewriter::notifyMatchFailure(), mlir::RewriterBase::notifyMatchFailure(), mlir::ConversionPatternRewriter::replaceOp(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
getNParallelLoopsAttrs()
static SmallVector<StringRef> getNParallelLoopsAttrs (unsigned nParallelLoops) static
Definition at line 31 of file TosaToLinalgNamed.cpp.
References mlir::getParallelIteratorTypeName().
Referenced by filterDynamicDims().
getValuesFromIntArrayAttribute()
template<typename T > static void getValuesFromIntArrayAttribute (ArrayAttr attr, SmallVector< T > & arrayValues) static
Definition at line 36 of file TosaToLinalgNamed.cpp.
Referenced by filterDynamicDims().